### ISSUE TITLE
使用了subsampling-scale-image-view加载大图，却没有声明，是不是不太好？

### ISSUE THREAD

**Issue by SwiftyWang** [SherlockGougou/BigImageViewPager#1]
其实就是对subsampling-scale-image-view一个简单的封装嘛。。
超大图、超长图、支持手势放大，区块复用加载这些核心feature都是subsampling-scale-image-view提供的，好歹你也在readme里面提下人家吧？

**Comment by SherlockGougou** [comment]
不好意思，马上加上。谢谢提醒。

**Comment by SherlockGougou** [comment]
已经加上了，再次感谢您的提醒😁
