### ISSUE TITLE
请问一下图片的高度你是怎么设置的，是动态这样

### ISSUE THREAD

**Issue by dary123** [SherlockGougou/BigImageViewPager#10]
请问一下图片的高度你是怎么设置的，是java动态这样设置吗
LinearLayout.LayoutParams params;
params = new LinearLayout.LayoutParams(width,height);
ll_signle.setLayoutParams(params);

如果是这样设置的，大神能不能告诉我参数width和height的单位是px,pt还是dp，我想使用这种方式设置图片原本的高度，但是就是使用imageview动态设置的高度和您的框架显示的高度有点差别，我现在知道图片的高度是288pt，直接传288进去貌似显示的高度太小了，到底应该288乘以多少然后传参进去呢

**Comment by SherlockGougou** [comment]
你是在修改源码嘛？还是有什么需求？你可以加群进行讨论（README底部二维码）
