### ISSUE TITLE
下载的图标会因为图片看不到

### ISSUE THREAD

**Issue by CaiJinFu** [SherlockGougou/BigImageViewPager#102]
比如这里设置下载的图标是黑色的，如果图片本身是黑的就看不到了，同样的情况也出现在是白色的时候，是不是可以像微信的图片那样处理，下面应该是设了一个透明度的view覆盖在上面

**Comment by CaiJinFu** [comment]
Demo总开启看图的最后一张，下载图标就看不到

**Comment by SherlockGougou** [comment]
所有的图标包括顶部的指示器，都是可以自定义背景或者图片的，可以参考ReadMe
