### ISSUE TITLE
保存多张url带附加参数的图片时永远只能保存一张图片

### ISSUE THREAD

**Issue by guodong89758** [SherlockGougou/BigImageViewPager#104]
例如：http://image.heyuedi.com/analysis/gmfwf-1590114901981.png?x-oss-process=image/resize,w_720
图片地址虽然不一样，但截取图片名称的逻辑只能得到resize,w_720，保存多张图片图库只会存在一张图片

**Comment by SherlockGougou** [comment]
后续会优化为使用url做md5处理作为文件名

**Comment by SherlockGougou** [comment]
已优化：
v4_6.0.1
androidx-6.0.2
