### ISSUE TITLE
错误: 找不到符号 符号:   类 CheckResult 位置: 类 GlideOptions	

### ISSUE THREAD

**Issue by asche910** [SherlockGougou/BigImageViewPager#11]
为啥我的是这样的😂， 依赖都添加了，gradle刷新也没问题。不会是因为我的项目是androidx的问题吧

**Comment by SherlockGougou** [comment]
请问你是用的v4版本的嘛？我没有在AndroidX上面测试过，稍后我测试一下。

**Comment by SherlockGougou** [comment]
OK，我测试发现，最新发布版本的glide4.8.0和AndroidX有冲突，所以本框架目前不会主动迁移到AndroidX。后面等glide发布了对AndroidX支持的正式版本后会更新。
