### ISSUE TITLE
.ico文件无法加载

### ISSUE THREAD

**Issue by OneGreenHand** [SherlockGougou/BigImageViewPager#114]
.ico后缀的无法加载一直转圈
但是我直接用glide是可以加载出来的

**Comment by SherlockGougou** [comment]
麻烦给个地址呢，我测试一下看看。

**Comment by OneGreenHand** [comment]
http://www.yzcopen.com/img/downPicture?pictureUrl=temp/img/2020-10-16/1602837599892favicon.ico
http://www.yzcopen.com/img/downPicture?pictureUrl=temp/img/2020-10-16/1602843312205favicon.ico

**Comment by SherlockGougou** [comment]
我使用glide直接加载依旧无法支持：
![image](https://user-images.githubusercontent.com/17920617/96392168-d5fd4a00-11ed-11eb-87d7-940a5d520565.png)

**Comment by OneGreenHand** [comment]
图片过期了，你可以用这个网址去生成一下，然后复制图片地址
http://www.favicon-icon-generator.com/favicon

**Comment by SherlockGougou** [comment]
好的，已经修复了，版本号：6.1.1
