### ISSUE TITLE
图片在放大时, 不能下拉关闭

### ISSUE THREAD

**Issue by Songsayit** [SherlockGougou/BigImageViewPager#118]
参考iPhone手机的图库. 发现他在图片放大后, 如果拉到顶部(底部), 他仍然是可以下拉(上拉)关闭.
修改代码FingerDragHelper.java 的83行改成下面那样就行了. 
请作者帮忙更新一下. 谢谢
 isIntercept = (imageView.atYEdge || (imageView.getScale() <= (imageView.getMinScale() + 0.001F)))
                                && (imageView.getMaxTouchCount() == 0 || imageView.getMaxTouchCount() == 1)
                                && Math.abs(ev.getRawY() - mDownY) > 2 * mTouchslop;
//                                && imageView.atYEdge);

**Comment by SherlockGougou** [comment]
其实是原本就是这么设计的，不过你的建议不错，我可以加个开关```setEnableDragCloseIngoreScale```，默认```false```需要的可以设置为```true```；

**Comment by Songsayit** [comment]
嗯. 谢谢.  主要现在的UI交互参考的都是iphone的. 所以需要麻烦一下你

**Comment by SherlockGougou** [comment]
已经增加了，版本号6.1.2

**Comment by Songsayit** [comment]
谢谢您

**Comment by puderty** [comment]
我看了这个，然后用了微信iOS的觉得它的体验更合理。区别在：
1，禁止向上滑动关闭的话应该如果一开始就在底部边缘，是不应该可以向上滑动的。
2，即使是在放大panning模式，如果已经滑动到顶部，也可以触发这个下拉关闭功能。

我的修改patch：

Index: library/src/main/java/cc/shinichi/library/view/helper/SubsamplingScaleImageViewDragClose.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- library/src/main/java/cc/shinichi/library/view/helper/SubsamplingScaleImageViewDragClose.java	(revision 332e5405a167fd141411e552bf26ed4b31dda6dd)
+++ library/src/main/java/cc/shinichi/library/view/helper/SubsamplingScaleImageViewDragClose.java	(date 1607753944000)
@@ -29,11 +29,6 @@
 import android.view.ViewConfiguration;
 import android.view.ViewParent;
 
-import androidx.annotation.AnyThread;
-import androidx.annotation.NonNull;
-import androidx.annotation.Nullable;
-import androidx.exifinterface.media.ExifInterface;
-
 import com.davemorrissey.labs.subscaleview.ImageViewState;
 import com.davemorrissey.labs.subscaleview.R.styleable;
 import com.davemorrissey.labs.subscaleview.decoder.CompatDecoderFactory;
@@ -54,6 +49,12 @@
 import java.util.concurrent.locks.ReadWriteLock;
 import java.util.concurrent.locks.ReentrantReadWriteLock;
 
+import androidx.annotation.AnyThread;
+import androidx.annotation.NonNull;
+import androidx.annotation.Nullable;
+import androidx.exifinterface.media.ExifInterface;
+import cc.shinichi.library.ImagePreview;
+
 /**
  * @author 工藤
  * @email qinglingou@gmail.com
@@ -910,9 +911,12 @@
                             float lastY = vTranslate.y;
                             fitToBounds(true);
                             atXEdge = lastX != vTranslate.x;
-                            atYEdge = lastY != vTranslate.y;
+                            boolean enableUpDragClose = ImagePreview.getInstance().isEnableUpDragClose();
+                            // 我的修改: 只允许从上面往下关闭，不允许往上滑关闭. 如果Y在边缘并且是向上滑动，则判断为Y不在边缘
+                            atYEdge = (lastY != vTranslate.y) && (enableUpDragClose || ((event.getY() - vCenterStart.y) > 0));
                             boolean edgeXSwipe = atXEdge && dx > dy && !isPanning;
-                            boolean edgeYSwipe = atYEdge && dy > dx && !isPanning;
+                            // 我的修改：仿微信，即使正在移动图像，如果到了顶部，也允许往下滑动关闭, 即对Y移动不判断是否在panning
+                            boolean edgeYSwipe = atYEdge && dy > dx;// && !isPanning;
                             boolean yPan = lastY == vTranslate.y && dy > offset * 3;
                             if (!edgeXSwipe && !edgeYSwipe && (!atXEdge || !atYEdge || yPan || isPanning)) {
                                 isPanning = true;
Index: library/src/main/java/cc/shinichi/library/view/helper/FingerDragHelper.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- library/src/main/java/cc/shinichi/library/view/helper/FingerDragHelper.java	(revision 332e5405a167fd141411e552bf26ed4b31dda6dd)
+++ library/src/main/java/cc/shinichi/library/view/helper/FingerDragHelper.java	(date 1607753123000)
@@ -12,7 +12,6 @@
 import android.widget.LinearLayout;
 
 import androidx.annotation.Nullable;
-
 import cc.shinichi.library.ImagePreview;
 import cc.shinichi.library.R;
 import cc.shinichi.library.view.nine.ViewHelper;
@@ -36,6 +35,7 @@
     private SubsamplingScaleImageViewDragClose imageView;
     private PhotoView imageGif;
     private float mDownY;
+    private boolean isFirstMoveAfterDown = true;
     private float mTranslationY;
     private float mLastTranslationY;
     private boolean isAnimate = false;
@@ -73,6 +73,7 @@
         switch (action) {
             case MotionEvent.ACTION_DOWN:
                 mDownY = ev.getRawY();
+                isFirstMoveAfterDown = false;
             case MotionEvent.ACTION_MOVE:
                 if (ImagePreview.getInstance().isEnableDragClose()) {
                     if (imageGif != null && imageGif.getVisibility() == View.VISIBLE) {
@@ -92,6 +93,12 @@
                                     && imageView.atYEdge;
                         }
                     }
+                    // 我的修改: 和微信表现一样：如果在放大模式并且不在顶部，滑动到顶部的时候这里可以拦截到事件
+                    // 此时mDownY应该重置为当前点，否则当前点离真正的按下点很远了直接view就被拖下来很远
+                    if (isIntercept && !isFirstMoveAfterDown) {
+                        mDownY = ev.getRawY();
+                        isFirstMoveAfterDown = true;
+                    }
                 }
                 break;
             default:
