### ISSUE TITLE
大神，你好，我想问下什么时候可以加个进度条改成数字显示百分比，就是一个白色的边框逐渐形成一个圆圈，中间显示加粗的当前进度百分比

### ISSUE THREAD

**Issue by dary123** [SherlockGougou/BigImageViewPager#12]
大神，你好，我想问下什么时候可以加个进度条改成数字显示百分比，就是一个白色的边框逐渐形成一个圆圈，中间显示加粗的当前进度百分比，还有，为啥我加了群，没人同意额

**Comment by SherlockGougou** [comment]
没有收到你的加群申请呀，你可以重新再试一下。另外你说的那个百分比只是UI样式而已，后面闲下来了可能会提供多种UI。

**Comment by SherlockGougou** [comment]
4.0.0已经支持自定义百分比view了，详情可参考Demo：https://github.com/SherlockGougou/BigImageViewPager/blob/master/sample/src/main/java/cc/shinichi/bigimageviewpager/MainActivity.java#L291
