### ISSUE TITLE
getGlideCacheFile的路径不完全正确

### ISSUE THREAD

**Issue by silentpride** [SherlockGougou/BigImageViewPager#122]
如果app配置了Glide的缓存路径，getGlideCacheFile取的文件目录就会有问题

图片加载的缓存目录
![image](https://user-images.githubusercontent.com/21210520/99956691-66b4e000-2dc1-11eb-90d1-fa1fc3e5988f.png)

getGlideCacheFile取文件目录
![image](https://user-images.githubusercontent.com/21210520/99956362-dd9da900-2dc0-11eb-8aa4-5155b34dca1a.png)

这样就导致点了【查看原图】，且原图顺利下载到本地，退出页面在查看图片，还会显示【查看原图】的按钮。
此时点了【查看原图】，进度会卡在1%一直不动。

**Comment by SherlockGougou** [comment]
> 如果app配置了Glide的缓存路径，getGlideCacheFile取的文件目录就会有问题
> 
> 图片加载的缓存目录
> ![image](https://user-images.githubusercontent.com/21210520/99956691-66b4e000-2dc1-11eb-90d1-fa1fc3e5988f.png)
> 
> getGlideCacheFile取文件目录
> ![image](https://user-images.githubusercontent.com/21210520/99956362-dd9da900-2dc0-11eb-8aa4-5155b34dca1a.png)
> 
> 这样就导致点了【查看原图】，且原图顺利下载到本地，退出页面在查看图片，还会显示【查看原图】的按钮。
> 此时点了【查看原图】，进度会卡在1%一直不动。
> 

有按照README配置GlideModule吗？

**Comment by silentpride** [comment]
> > 如果app配置了Glide的缓存路径，getGlideCacheFile取的文件目录就会有问题
> > 图片加载的缓存目录
> > ![image](https://user-images.githubusercontent.com/21210520/99956691-66b4e000-2dc1-11eb-90d1-fa1fc3e5988f.png)
> > getGlideCacheFile取文件目录
> > ![image](https://user-images.githubusercontent.com/21210520/99956362-dd9da900-2dc0-11eb-8aa4-5155b34dca1a.png)
> > 这样就导致点了【查看原图】，且原图顺利下载到本地，退出页面在查看图片，还会显示【查看原图】的按钮。
> > 此时点了【查看原图】，进度会卡在1%一直不动。
> 
> 有按照README配置GlideModule吗？


有的
![image](https://user-images.githubusercontent.com/21210520/99959485-0ffdd500-2dc6-11eb-89bc-182d5a5376bd.png)

**Comment by silentpride** [comment]
我强行把AppGlideModule配置里的的默认缓存目录换成这个
File(context.cacheDir, DiskCache.Factory.DEFAULT_DISK_CACHE_DIR)
就好了。

这里建议还是不要写死，ImagePreviewAdapter的onLoadFailed里，saveDir可能是变的；getGlideCacheFile里判断是否有缓存读的是File(context.getCacheDir(), DiskCache.Factory.DEFAULT_DISK_CACHE_DIR)，容易出现缓存判断不准确的问题。

另外：
https://github.com/SherlockGougou/BigImageViewPager/issues/52#issue-448404812
https://github.com/SherlockGougou/BigImageViewPager/issues/109#issue-648107892

这两个问题特别影响国际化的app，建议抽时间修复。

**Comment by SherlockGougou** [comment]
国际化已增加。
