### ISSUE TITLE
有用到kotlin 集成发现点击查看原图，加载还是1%的，看这里

### ISSUE THREAD

**Issue by zhyazaq** [SherlockGougou/BigImageViewPager#130]
集成经验：根据集成4步都已经集成完了，如果使用kotlin的兄弟别忘了在 app 里面的build.gradle 中添加kotlin的
dependencies {
 kapt 'com.github.bumptech.glide:compiler:4.11.0'
}

**Comment by Laze1** [comment]
我也遇到了这个问题，Step 3照做了
也集成了com.github.bumptech.glide:compiler:4.12.0
也是kotlin

**Comment by XuHX** [comment]
添加了还是1%

**Comment by tututututututu** [comment]
+1  还是卡在1%

**Comment by SherlockGougou** [comment]
release: androidx-7.0.5
主要解决了重定向的地址进度卡在1%问题，有问题可以再回复。
