### ISSUE TITLE
gradle编译太慢

### ISSUE THREAD

**Issue by fuchengxin** [SherlockGougou/BigImageViewPager#131]
BigImageViewPager功能还是挺完善的，就是使用这个库之后，gradle编译一次都6分钟起步，有点费时，去除或者换成别的库 都是秒编译，还是有待改进

**Comment by SherlockGougou** [comment]
大概率应该是网络和你的gradle依赖同步策略原因。暂未接到别人反馈同样问题。

**Comment by fuchengxin** [comment]
> 大概率应该是网络和你的gradle依赖同步策略原因。暂未接到别人反馈同样问题。
