### ISSUE TITLE
Demo中点击【相册选图】直接崩溃

### ISSUE THREAD

**Issue by zqlq4ever** [SherlockGougou/BigImageViewPager#133]
机型：小米8
系统：MIUI 12 Android 10
错误日志:
![错误](https://user-images.githubusercontent.com/37474811/104160156-9b413180-542b-11eb-9349-adae26df43d3.png)

**Comment by SherlockGougou** [comment]
图片框架版本老旧的问题，Demo选图功能只是抛个砖，具体请使用自己的选图框架。
