### ISSUE TITLE
状态偶尔会重置，导致无法下拉关闭

### ISSUE THREAD

**Issue by chengfan2017** [SherlockGougou/BigImageViewPager#134]
![image](https://user-images.githubusercontent.com/19389193/104985046-0782ed00-5a4b-11eb-839e-46bb3b847818.png)
![image](https://user-images.githubusercontent.com/19389193/104985065-12d61880-5a4b-11eb-9a77-2fef4dc49f46.png)

概率出现状态会重置false，打开之前已经设置为true

**Comment by chengfan2017** [comment]
![image](https://user-images.githubusercontent.com/19389193/104986073-41ed8980-5a4d-11eb-9f83-e89db7eba717.png)
问题定位到了，就是这里有时候会延迟执行，等到下次打开其他图片的时候，这里就会重置状态

**Comment by SherlockGougou** [comment]
感谢反馈，OnStop、OnDestory是有执行延时存在的，所以可能在短时间内（10s左右）再次打开可能会被重置。下个版本修复。再次感谢~

**Comment by SherlockGougou** [comment]
androidx-6.1.4 再试试

**Comment by chengfan2017** [comment]
@SherlockGougou 6.1.4没发现这个问题了，点赞，这处理速度
