### ISSUE TITLE
pictures rotating

### ISSUE THREAD

**Issue by wangshufu** [SherlockGougou/BigImageViewPager#135]
I have a problem,In Android 10, view the HEIC format image rotation

**Comment by SherlockGougou** [comment]
本地图片还是网络图片？

**Comment by wangshufu** [comment]
是heic格式的图片,不管是网络还是本地,查看都会逆时针旋转90度
给你一个测试的heic网络图片
http://link.yun.tilldream.com/IMG_211608572.heic

**Comment by SherlockGougou** [comment]
感谢反馈，下个版本我修复一下。

**Comment by wangshufu** [comment]
大佬,有定位哪里有问题吗?非常着急修复这个问题,定位到了能不能先告诉我,非常感谢

**Comment by SherlockGougou** [comment]
你加一下README底下的QQ群

**Comment by SherlockGougou** [comment]
上面那个图片地址，我在demo中测试没问题呀。

**Comment by wangshufu** [comment]
demo测试是可以,是我的问题,不好意思!!!
经测试得用Glide显示,并且得用Glide版本11
