### ISSUE TITLE
Attempt to read from field 'float android.graphics.PointF.x' on a null object reference

### ISSUE THREAD

**Issue by guodong89758** [SherlockGougou/BigImageViewPager#137]
androidx-6.1.4  在错误统计平台上看到不少这两个问题的错误日志，自测没测出来，应该是偶现的问题，希望能够处理下，谢谢！
java.lang.NullPointerException:Attempt to read from field 'float android.graphics.PointF.x' on a null object reference
android.graphics.PointF.set(PointF.java:54)
cc.shinichi.library.view.helper.SubsamplingScaleImageViewDragClose.boolean onTouchEvent(android.view.MotionEvent)(SubsamplingScaleImageViewDragClose.java:20)
android.view.View.dispatchTouchEvent(View.java:11798)
android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2968)
android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2657)
android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2968)
android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2657)
android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2968)
android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2657)
android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2968)
android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2657)
android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2968)
android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2657)
android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2968)
android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2657)
android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2968)
android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2657)
android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2968)
android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2657)
android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2968)
android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2657)
com.billy.android.swipe.SmartSwipeWrapper.boolean dispatchTouchEvent(android.view.MotionEvent)(SmartSwipeWrapper.java:3)
android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2968)
android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2657)
com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:485)
com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1842)
android.app.Activity.dispatchTouchEvent(Activity.java:3341)
androidx.appcompat.view.WindowCallbackWrapper.boolean dispatchTouchEvent(android.view.MotionEvent)(WindowCallbackWrapper.java:1)
java.lang.reflect.Method.invoke(Native Method)
org.chromium.base.ApplicationStatus$d.invoke(TbsJavaCore:194)
java.lang.reflect.Proxy.invoke(Proxy.java:913)
$Proxy23.dispatchTouchEvent(Unknown Source)
com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:445)
android.view.View.dispatchPointerEvent(View.java:12037)
android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4883)
android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4678)
android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4182)
android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4235)
android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4201)
android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4328)
android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4209)
android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4385)
android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4182)
android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4235)
android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4201)
android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4209)
android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4182)
android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6761)
android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6735)
android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6696)
android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6873)
android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:187)
android.os.MessageQueue.nativePollOnce(Native Method)
android.os.MessageQueue.next(MessageQueue.java:325)
android.os.Looper.loop(Looper.java:142)
android.app.ActivityThread.main(ActivityThread.java:6707)
java.lang.reflect.Method.invoke(Native Method)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:886)

另一个问题也有出现，统计到的没上面那个多
java.lang.NullPointerException
Attempt to invoke virtual method 'java.lang.Object java.util.HashMap.remove(java.lang.Object)' on a null object reference
cc.shinichi.library.view.ImagePreviewAdapter.java.lang.Object instantiateItem(android.view.ViewGroup,int)(ImagePreviewAdapter.java:28)
androidx.viewpager.widget.ViewPager.androidx.viewpager.widget.ViewPager$ItemInfo addNewItem(int,int)(ViewPager.java:3)
androidx.viewpager.widget.ViewPager.void populate(int)(ViewPager.java:32)
androidx.viewpager.widget.ViewPager.void populate()(ViewPager.java:1)
androidx.viewpager.widget.ViewPager$3.void run()(ViewPager.java:2)
android.view.Choreographer$CallbackRecord.run(Choreographer.java:1256)
android.view.Choreographer.doCallbacks(Choreographer.java:995)
android.view.Choreographer.doFrame(Choreographer.java:883)
android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1224)
android.os.Handler.handleCallback(Handler.java:900)
android.os.Handler.dispatchMessage(Handler.java:103)
android.os.Looper.loop(Looper.java:219)
android.app.ActivityThread.main(ActivityThread.java:8387)
java.lang.reflect.Method.invoke(Native Method)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)

**Comment by LeonShannon** [comment]
目前我崩溃最多的就是这个了。作者大大可以帮忙维护下这个问题吗？

**Comment by protectedMan** [comment]
同此问题

**Comment by ryanZhange** [comment]
# main(2)
java.lang.NullPointerException
Attempt to read from field 'float android.graphics.PointF.x' on a null object reference
解析原始
1
android.graphics.PointF.set(PointF.java:54)
2
cc.shinichi.library.view.helper.SubsamplingScaleImageViewDragClose.boolean onTouchEvent(android.view.MotionEvent)(SubsamplingScaleImageViewDragClose.java:743)

**Comment by SherlockGougou** [comment]
6.2.1版本发布了，你们再试一下呢，如果有问题再反馈。
