### ISSUE TITLE
我想做一个长按弹窗，但是弹窗无法出现

### ISSUE THREAD

**Issue by yangqb** [SherlockGougou/BigImageViewPager#138]
我想做一个长按弹窗，但是弹窗无法出现

**Comment by SherlockGougou** [comment]
setBigImageLongClickListener 回调的参数中有上下文，使用这个上下文即可。

**Comment by yangqb** [comment]
好的，谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年3月15日(星期一) 上午10:12
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [SherlockGougou/BigImageViewPager] 我想做一个长按弹窗，但是弹窗无法出现 (#138)





 
setBigImageLongClickListener 回调的参数中有上下文，使用这个上下文即可。
