### ISSUE TITLE
图裂与黑屏情况

### ISSUE THREAD

**Issue by fuys123** [SherlockGougou/BigImageViewPager#142]
1、刚发出去的图片立即查看显示会出现图裂的加载失败样式，跟踪发现显示的本地地址图片存在，就是偶现出现，概率不小。
2、左右滑动出现黑屏情况 ，直接单点出现黑屏图片反而没事，也是偶现概率。

**Comment by SherlockGougou** [comment]
您好，是否存在重复图片呢？如果重复图片的话，是会出现黑屏的情况，属于框架机制。详情见指定issue[https://github.com/SherlockGougou/BigImageViewPager/issues/107](url)

**Comment by fuys123** [comment]
> 您好，是否存在重复图片呢？如果重复图片的话，是会出现黑屏的情况，属于框架机制。详情见指定issue[https://github.com/SherlockGougou/BigImageViewPager/issues/107](url)

是的存在重复图片，但若是本地图片的话不该这么处理；第二问题比较突出 可以优先处理。

**Comment by SherlockGougou** [comment]
好的，稍等一会。

**Comment by fuys123** [comment]
> 好的，稍等一会。
这负责的态度很赞！谢谢。

**Comment by SherlockGougou** [comment]
试一下androidx-6.1.5版本呢

**Comment by fuys123** [comment]
> 试一下androidx-6.1.5版本呢

嗯嗯 试了给您反馈结果。

**Comment by fuys123** [comment]
> 试一下androidx-6.1.5版本呢

本地发出去出现查看原图的标签了 但是点击只加载1%不动的情况 判断应该出现问题了还是我这边需要改什么参数

**Comment by SherlockGougou** [comment]
好的，我试一下本地图片。

**Comment by SherlockGougou** [comment]
我测试本地图片是没问题的：
```
                // 仅需一行代码,默认配置为：
                //      显示顶部进度指示器、
                //      显示右侧下载按钮、
                //      隐藏左侧关闭按钮、
                //      开启点击图片关闭、
                //      关闭下拉图片关闭、
                //      加载方式为手动模式
                //      加载原图的百分比在底部

                // 一行代码即可实现大部分需求，如需定制，可参考下面自定义的代码：
                ImagePreview.getInstance().setContext(MainActivity.this).setImageList(Arrays.asList(images)).start();
```

不需要特殊设置，你那边都是本地图片还是说网络和本地可能混合出现呢？

**Comment by fuys123** [comment]
> 我测试本地图片是没问题的：
> 
> ```
>                 // 仅需一行代码,默认配置为：
>                 //      显示顶部进度指示器、
>                 //      显示右侧下载按钮、
>                 //      隐藏左侧关闭按钮、
>                 //      开启点击图片关闭、
>                 //      关闭下拉图片关闭、
>                 //      加载方式为手动模式
>                 //      加载原图的百分比在底部
> 
>                 // 一行代码即可实现大部分需求，如需定制，可参考下面自定义的代码：
>                 ImagePreview.getInstance().setContext(MainActivity.this).setImageList(Arrays.asList(images)).start();
> ```
> 
> 不需要特殊设置，你那边都是本地图片还是说网络和本地可能混合出现呢？

我知道原因了 6.1.5版本如果再使用因为相同图片地址导致黑屏的代码的话就会出现这问题。我这边去掉了这代码正常了。

**Comment by SherlockGougou** [comment]
好的，我就先关闭了哈，有问题再回复。
