### ISSUE TITLE
java.lang.NullPointerException Attempt to invoke virtual method 'java.lang.String java.lang.String.trim()' on a null object reference cc.shinichi.library.view.ImagePreviewAdapter.instantiateItem(ImagePreviewAdapter.java:61)

### ISSUE THREAD

**Issue by Victory-Over** [SherlockGougou/BigImageViewPager#144]
这个错误在我们APP友盟统计中排行TOP2 能不能麻烦修复一下?
java.lang.NullPointerException
Attempt to invoke virtual method 'java.lang.String java.lang.String.trim()' on a null object reference
cc.shinichi.library.view.ImagePreviewAdapter.instantiateItem(ImagePreviewAdapter.java:61)

**Comment by SherlockGougou** [comment]
这个问题需要你来排查传入的url问题。
