### ISSUE TITLE
About default placeholder

### ISSUE THREAD

**Issue by devzwy** [SherlockGougou/BigImageViewPager#15]
@SherlockGougou 
Thanks to the resources provided by the author, I personally feel that we can optimize the following problems:
The default placeholder when the picture address is empty or the picture can not be successfully loaded.

**Comment by SherlockGougou** [comment]
Good idea!Coming soon...

**Comment by SherlockGougou** [comment]
2.2.2版本已支持设置加载失败时的占位图：
`public ImagePreview setErrorPlaceHolder(int errorPlaceHolderResId)`

**Comment by devzwy** [comment]
3Q
