### ISSUE TITLE
图片加载框架建议抽出接口，而不是强依赖`glide`

### ISSUE THREAD

**Issue by liyujiang-gzu** [SherlockGougou/BigImageViewPager#156]

**Comment by 4what2do** [comment]
kotlin 插件的版本太高了  能否不要强制指定kt的插件版本 提高一下兼容性

**Comment by SherlockGougou** [comment]
> 

可以看一下编译报的错吗？

**Comment by 4what2do** [comment]
刚改回去了，我的插件版本是1.4.10，你的版本是1.6，编译肯定挂了

因为插件不是依赖库 不知道咋强制版本

**Comment by SherlockGougou** [comment]
你测试一下snapshot版本：
```
implementation 'com.github.SherlockGougou:BigImageViewPager:master-SNAPSHOT'
```

**Comment by 4what2do** [comment]
👌我立马测一下

**Comment by 4what2do** [comment]
![image](https://user-images.githubusercontent.com/11016518/164647797-05fc94bf-a9be-4739-83fe-f0c732e42c96.png)
其他的androidx库又冲突了，算了不折腾了，我直接改一下源码

**Comment by tututututututu** [comment]
希望能外面接入其他图片框架

**Comment by SherlockGougou** [comment]
https://github.com/SherlockGougou/BigImageViewPager/issues/165
