### ISSUE TITLE
Attempt to read from field 'float android.graphics.PointF.x' on a null object reference

### ISSUE THREAD

**Issue by protectedMan** [SherlockGougou/BigImageViewPager#160]
java.lang.NullPointerException
Attempt to read from field 'float android.graphics.PointF.x' on a null object reference
android.graphics.PointF.set(PointF.java:54)
cc.shinichi.library.view.helper.SubsamplingScaleImageViewDragClose.onTouchEvent(SubsamplingScaleImageViewDragClose.java:743)
android.view.View.dispatchTouchEvent(View.java:13698)
android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3249)
android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2938)
android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3249)
...

**Comment by protectedMan** [comment]
版本androidx-6.1.6

**Comment by liuxuebing2010** [comment]
我们也遇到了
报错的设备Realme V15 RMX3092
操作系统版本:11

**Comment by SherlockGougou** [comment]
6.2.1版本发布了，你们再试一下呢，如果有问题再反馈。
