### ISSUE TITLE
项目使用的是？ com.davemorrissey.labs:subsampling-scale-image-view:3.10.0

### ISSUE THREAD

**Issue by liuxuebing2010** [SherlockGougou/BigImageViewPager#161]
Duplicate class com.davemorrissey.labs.subscaleview.BuildConfig found in modules jetified-subsampling-scale-image-view-3.10.0-runtime.jar (com.davemorrissey.labs:subsampling-scale-image-view:3.10.0) and jetified-subsampling-scale-image-view-androidx-3.10.0-runtime.jar (com.davemorrissey.labs:subsampling-scale-image-view-androidx:3.10.0)

**Comment by HaleLiu** [comment]
A failure occurred while executing com.android.build.gradle.internal.tasks.CheckDuplicatesRunnable
   > Duplicate class com.davemorrissey.labs.subscaleview.BuildConfig found in modules jetified-subsampling-scale-image-view-3.10.0-runtime (com.davemorrissey.labs:subsampling-scale-image-view:3.10.0) and jetified-subsampling-scale-image-view-androidx-3.10.0-runtime (com.davemorrissey.labs:subsampling-scale-image-view-androidx:3.10.0)
     Duplicate class com.davemorrissey.labs.subscaleview.ImageSource found in modules jetified-subsampling-scale-image-view-3.10.0-runtime (com.davemorrissey.labs:subsampling-scale-image-view:3.10.0) and jetified-subsampling-scale-image-view-androidx-3.10.0-runtime (com.davemorrissey.labs:subsampling-scale-image-view-androidx:3.10.0)
     Duplicate class com.davemorrissey.labs.subscaleview.ImageViewState found in modules jetified-subsampling-scale-image-view-3.10.0-runtime (com.davemorrissey.labs:subsampling-scale-image-view:3.10.0) and jetified-subsampling-scale-image-view-androidx-3.10.0-runtime (com.davemorrissey.labs:subsampling-scale-image-view-androidx:3.10.0)
     Duplicate class com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView found in modules jetified-subsampling-scale-image-view-3.10.0-runtime (com.davemorrissey.labs:subsampling-scale-image-view:3.10.0) and jetified-subsampling-scale-image-view-androidx-3.10.0-runtime (com.davemorrissey.labs:subsampling-scale-image-view-androidx:3.10.0)
     Duplicate class com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$1 found in modules jetified-subsampling-scale-image-view-3.10.0-runtime (com.davemorrissey.labs:subsampling-scale-image-view:3.10.0) and jetified-subsampling-scale-image-view-androidx-3.10.0-runtime (com.davemorrissey.labs:subsampling-scale-image-view-androidx:3.10.0)
     Duplicate class com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$2 found in modules jetified-subsampling-scale-image-view-3.10.0-runtime (com.davemorrissey.labs:subsampling-scale-image-view:3.10.0) and jetified-subsampling-scale-image-view-androidx-3.10.0-runtime (com.davemorrissey.labs:subsampling-scale-image-view-androidx:3.10.0)

**Comment by liuxuebing2010** [comment]
api ("com.github.SherlockGougou:BigImageViewPager:androidx-6.2.0"){
        exclude group:'com.davemorrissey.labs',module:'subsampling-scale-image-view'
    }
移除多余的

**Comment by SherlockGougou** [comment]
可以选择保留自己的或者是保留项目中的。
