### ISSUE TITLE
Attempt to read from field 'float android.graphics.PointF.x' on a null object reference  android.graphics.PointF.set(PointF.java:54)

### ISSUE THREAD

**Issue by wstcwcsbl** [SherlockGougou/BigImageViewPager#163]
java.lang.NullPointerException
Attempt to read from field 'float android.graphics.PointF.x' on a null object reference
android.graphics.PointF.set(PointF.java:54)
cc.shinichi.library.view.helper.SubsamplingScaleImageViewDragClose.onTouchEvent(SubsamplingScaleImageViewDragClose.java:21)
android.view.View.dispatchTouchEvent(View.java:12632)
android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2765)

**Comment by ThanatosDan** [comment]
我也遇到了该问题

**Comment by SherlockGougou** [comment]
6.2.0是否还有问题呢？

**Comment by zhaobinsir** [comment]
+1

**Comment by SherlockGougou** [comment]
6.2.1版本发布了，你们再试一下呢，如果有问题再反馈。
