### ISSUE TITLE
v6.2.0 NullPointerException

### ISSUE THREAD

**Issue by Victory-Over** [SherlockGougou/BigImageViewPager#166]
更新后还是有空指针现象
1、
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.String.trim()' on a null object reference
	at cc.shinichi.library.view.ImagePreviewAdapter.instantiateItem(ImagePreviewAdapter.java:295)

2、java.lang.RuntimeException: Unable to start activity ComponentInfo{com.piaxiya.app/cc.shinichi.library.view.ImagePreviewActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equalsIgnoreCase(java.lang.String)' on a null object reference

**Comment by SherlockGougou** [comment]
老哥是群里那位吧，我给与方案后现在怎么样了呢？望回复。
