### ISSUE TITLE
基础功能

### ISSUE THREAD

**Issue by ncworm** [SherlockGougou/BigImageViewPager#17]
有点击事件监听和长按事件监听吗？没看到有加入这个功能

**Comment by SherlockGougou** [comment]
你好 这个正在添加 今天会推个新版本

**Comment by SherlockGougou** [comment]
![image](https://user-images.githubusercontent.com/17920617/50208547-66796200-03ac-11e9-81e8-3861eb88bc28.png)
 请问是需要的这样的嘛？

**Comment by SherlockGougou** [comment]
你好 这个回调已经加上了 请看README
