### ISSUE TITLE
点击查看原图，加载还是1%

### ISSUE THREAD

**Issue by XuHX** [SherlockGougou/BigImageViewPager#170]
![screenshot](https://user-images.githubusercontent.com/25903912/151297278-c0c2f156-9774-4c49-a379-91dec49da7f6.png)
![2022-01-27_132825](https://user-images.githubusercontent.com/25903912/151297455-9fc09ef3-658e-48bb-ab1a-b611b7b4a889.jpg)

**Comment by SherlockGougou** [comment]
你这不是使用了kotlin的嘛？annotationProcessor改成katp

**Comment by XuHX** [comment]
> 
改了也还是这种情况

**Comment by SherlockGougou** [comment]
```
@GlideModule
public class MyAppGlideModule extends AppGlideModule {
  @Override
  public void registerComponents(@NonNull Context context, @NonNull Glide glide, @NonNull Registry registry) {
    super.registerComponents(context, glide, registry);

    // 替换底层网络框架为okhttp3，这步很重要！如果不添加会无法正常显示原图的加载百分比，或者卡在1%
    // 如果你的app中已经存在了自定义的GlideModule，你只需要把这一行代码，添加到对应的重载方法中即可。
    registry.replace(GlideUrl.class, InputStream.class, new OkHttpUrlLoader.Factory(ProgressManager.getOkHttpClient()));
  }
}
```
这个做了吗？

**Comment by XuHX** [comment]
> ```
> @GlideModule
> public class MyAppGlideModule extends AppGlideModule {
>   @Override
>   public void registerComponents(@NonNull Context context, @NonNull Glide glide, @NonNull Registry registry) {
>     super.registerComponents(context, glide, registry);
> 
>     // 替换底层网络框架为okhttp3，这步很重要！如果不添加会无法正常显示原图的加载百分比，或者卡在1%
>     // 如果你的app中已经存在了自定义的GlideModule，你只需要把这一行代码，添加到对应的重载方法中即可。
>     registry.replace(GlideUrl.class, InputStream.class, new OkHttpUrlLoader.Factory(ProgressManager.getOkHttpClient()));
>   }
> }
> ```
> 
> 这个做了吗？
做了

**Comment by SherlockGougou** [comment]
看一下你的这个自定义GlideModule有没有被引用的，如果没有说明没生效。

**Comment by XuHX** [comment]
> 

解决了，原图地址错误，查看原图显示1%

**Comment by SherlockGougou** [comment]
好的。
