### ISSUE TITLE
崩溃问题

### ISSUE THREAD

**Issue by Yangqingchun** [SherlockGougou/BigImageViewPager#176]
我把txt文件后缀改为了png，然后调用接口打开的话，会造成整个程序崩溃，能够规避吗..

**Comment by SherlockGougou** [comment]
我这边试试🤣> 我把txt文件后缀改为了png，然后调用接口打开的话，会造成整个程序崩溃，能够规避吗..

**Comment by SherlockGougou** [comment]
你好，我这边测试了，把一个远端的txt文件更改后缀为png，没有发生报错呢，只是一直加载中而已。你可以贴一下报错的内容吗？

**Comment by Yangqingchun** [comment]
你好，我又试了一下，确实是一直处于加载状态，是可以的，但现在又遇到了一个新问题。。就是在打开.bmp格式的图片时，会默认使用原生图库打开。。但是如果是处于列表模式下，通过左右滑动到那张图片的时候，就可以正常浏览

**Comment by Yangqingchun** [comment]
sorry，我看了一下我的代码，是我的问题。。我现在还有一个问题，就是打开那种异形图片应该怎么适配呢，现在打开那种小图片的话，会被拉伸到整个屏幕上显示，很别扭。。

**Comment by SherlockGougou** [comment]
> sorry，我看了一下我的代码，是我的问题。。我现在还有一个问题，就是打开那种异形图片应该怎么适配呢，现在打开那种小图片的话，会被拉伸到整个屏幕上显示，很别扭。。

可以截图看一下嘛？

**Comment by Yangqingchun** [comment]
> > sorry，我看了一下我的代码，是我的问题。。我现在还有一个问题，就是打开那种异形图片应该怎么适配呢，现在打开那种小图片的话，会被拉伸到整个屏幕上显示，很别扭。。
> 
> 可以截图看一下嘛？

![1658453533657](https://user-images.githubusercontent.com/33993115/180342394-3a18fa94-db79-4a19-9396-440752b22add.jpg)
这张图片实际是一个54*54的图片，但被拉伸到整个屏幕了

**Comment by Yangqingchun** [comment]
![1658454564815](https://user-images.githubusercontent.com/33993115/180344229-e3fa7fcb-84f9-4de9-a49a-4cdb5583162e.jpg)
我尝试着修改了一下您项目的源码，将图里标注的地方都修改为“SubsamplingScaleImageViewDragClose.SCALE_TYPE_CENTER_INSIDE”模式了，这样我试着打开那种异形图片是可以的，不知道这样写会有什么影响吗？

**Comment by Yangqingchun** [comment]
![1658454564815](https://user-images.githubusercontent.com/33993115/180344229-e3fa7fcb-84f9-4de9-a49a-4cdb5583162e.jpg)
我尝试着修改了一下您项目的源码，将图里标注的地方都修改为“SubsamplingScaleImageViewDragClose.SCALE_TYPE_CENTER_INSIDE”模式了，这样我试着打开那种异形图片是可以的，不知道这样写会有什么影响吗？

**Comment by Yangqingchun** [comment]
打开本地的图片，概现图片加载失败，报错日志如下
![image](https://user-images.githubusercontent.com/33993115/181703205-848cd75f-c7c6-4021-bcae-59c42c65f6c8.png)

这是错误现象：
![image](https://user-images.githubusercontent.com/33993115/181703269-fab758ee-47e2-49b5-81f9-0b471a087ede.png)

大佬，有重新加载按钮吗，想在这种情况下加一个重新加载的按钮

**Comment by SherlockGougou** [comment]
不错的建议，我考虑一下。
