### ISSUE TITLE
无法加载不受信任的证书 https图片 

### ISSUE THREAD

**Issue by magicLanjie** [SherlockGougou/BigImageViewPager#18]
javax.net.ssl.SSLHandshakeException(com.android.org.bouncycastle.jce.exception.ExtCertPathValidatorException: Could not validate certificate: Certific

**Comment by SherlockGougou** [comment]
麻烦提供一下图片链接，谢谢。

**Comment by magicLanjie** [comment]
https://magiclanjie1920.io2c.com/static/images/bar/3.png

**Comment by SherlockGougou** [comment]
请问使用的是glide v3 还是 glide v4？

**Comment by magicLanjie** [comment]
![image](https://user-images.githubusercontent.com/31203442/50260359-9a06cb80-0442-11e9-9e99-126a370896b2.png)

**Comment by magicLanjie** [comment]
我设置了的都哇

**Comment by SherlockGougou** [comment]
你之前的图片加载用的是什么？还有就是，项目之前有木有依赖过okhttp？版本是多少？

**Comment by magicLanjie** [comment]
Okhttp3 然后用的是glide 4.8

**Comment by SherlockGougou** [comment]
okhttp 具体版本呢？

**Comment by magicLanjie** [comment]
我用您的demo可以！ 可能是我那个姿势没对，我自己在研究一下。谢谢您的指导

**Comment by SherlockGougou** [comment]
恩恩，有问题再说哈；okhttp3的版本过低，是有这个可能的，推荐使用okhttp3的最新版本：
implementation 'com.squareup.okhttp3:okhttp:3.11.0'
