### ISSUE TITLE
exception= lateinit property imagePreviewAdapter has not been initialized

### ISSUE THREAD

**Issue by HelloJokerWord** [SherlockGougou/BigImageViewPager#180]
0 | Error List:
-- | --
1 | java.lang.RuntimeException:Unable to start activity ComponentInfo{com.hpc.happy.chat.lite/cc.shinichi.library.view.ImagePreviewActivity}: j.n: lateinit property imagePreviewAdapter has not been initialized
2 | ......
3 | Cause by:
4 | cc.shinichi.library.view.ImagePreviewActivity.finish(:7)
5 | android.app.Activity.finishAfterTransition(Activity.java:6626)

**Comment by SherlockGougou** [comment]
请问是如何发生的呢？

**Comment by HelloJokerWord** [comment]
> 请问是如何发生的呢？

是奔溃日志抓到的，测试本身没有测出，聪日志上看，有点像是打开大图查看的时候，可能网络很卡怎么的，就很快速的就杀死进程，后台出了个崩溃的

**Comment by HelloJokerWord** [comment]
> 请问是如何发生的呢？

<img width="1077" alt="image" src="https://user-images.githubusercontent.com/18359626/207217604-24a75bd1-edea-4f6b-83e2-f1d03198cf6f.png">

**Comment by HelloJokerWord** [comment]
> 出现的次数多吗？

不多，就一两次，很极端的

**Comment by HelloJokerWord** [comment]
> 出现的次数多吗？

还有一个问题，也可以帮忙看下。
<img width="1241" alt="image" src="https://user-images.githubusercontent.com/18359626/207218070-ef3294a1-8a3a-49e0-9027-ab10aad5b955.png">
<img width="1250" alt="image" src="https://user-images.githubusercontent.com/18359626/207218171-2942fbec-933a-4cd0-9905-b7bb420a1242.png">
也是很极端的，有那么一两次

**Comment by SherlockGougou** [comment]
OK，我这边看看。

**Comment by HelloJokerWord** [comment]
> 出现的次数多吗？

我用户量的话大概1-2K左右

**Comment by HelloJokerWord** [comment]
> OK，我这边看看。

好的，谢谢

**Comment by HelloJokerWord** [comment]
> OK，我这边看看。

大佬，这两个奔溃，我感觉要么?.finish ， 要么try cache就好了。因为这两天发版想带上，嘻嘻。这两个奔溃之前的三四个版本都会有的。不过都很少，就一两个比较极端的。

**Comment by SherlockGougou** [comment]
7.0.6发布了，针对以上问题修复，你可以看变更记录。

**Comment by HelloJokerWord** [comment]
> 7.0.6发布了，针对以上问题修复，你可以看变更记录。

好的，谢谢大佬

**Comment by HelloJokerWord** [comment]
> 7.0.6发布了，针对以上问题修复，你可以看变更记录。

大佬，我这边还有个这个奔溃日志，有空帮忙看看。
<img width="1231" alt="image" src="https://user-images.githubusercontent.com/18359626/208116613-999197d7-2864-4e0a-9d68-a0c6c2b833a3.png">
<img width="1249" alt="image" src="https://user-images.githubusercontent.com/18359626/208116862-988e0023-6898-4146-899c-eeb1cd72c3aa.png">

Java crash handler caught exception: Index: 4, Size: 0 java.util.ArrayList.get(ArrayList.java:437) cc.shinichi.library.view.ImagePreviewActivity$a.onPageSelected(:6) g.d0.a.b.dispatchOnPageSelected(Unknown Source:28) g.d0.a.b.scrollToItem(Unknown Source:37) g.d0.a.b.setCurrentItemInternal(Unknown Source:106) g.d0.a.b.onTouchEvent(Unknown Source:295) android.view.View.dispatchTouchEvent(View.java:13699) android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3243) android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2924) android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3249) android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2938) android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3249) android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2938) android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3249) android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2938) android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3249) android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2938) android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3249) android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2938) android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3249) android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2938) com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:741) com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:2013) android.app.Activity.dispatchTouchEvent(Activity.java:4180) g.b.f.h.dispatchTouchEvent(Unknown Source:2) com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:687) android.view.View.dispatchPointerEvent(View.java:13962) android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:6420) android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6215) android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5604) android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5657)
