### ISSUE TITLE
在 Android X 版本中，依赖也应该使用 Android X版本

### ISSUE THREAD

**Issue by HenryWu01** [SherlockGougou/BigImageViewPager#181]
我通过 gradle 引用 ``com.github.SherlockGougou:BigImageViewPager:androidx-7.0.6`` 之后发现依赖的是 ``com.davemorrissey.labs:subsampling-scale-image-view:3.10.0`` , 因为我有别的依赖使用的Android X版本的 ``subsampling-scale-image-view-androidx``，发生了 Duplicate class 的错误。

Android X 版本的 BigImageViewPager 应该依赖 ``com.davemorrissey.labs:subsampling-scale-image-view-androidx:3.10.0`` 而不是 ``com.davemorrissey.labs:subsampling-scale-image-view:3.10.0``

**Comment by SherlockGougou** [comment]
OK，这个问题我近期尽快修复。

Henry Wu ***@***.***>于2022年12月19日 周一22:33写道：

**Comment by HenryWu01** [comment]
> OK，这个问题我近期尽快修复。
>> 收到，谢谢大佬。这个库真的很好用~把之前用的很 Buggy 的库换成这个了，瞬间舒服了很多

**Comment by SherlockGougou** [comment]
该问题已解决。
