### ISSUE TITLE
关于图片保存问题

### ISSUE THREAD

**Issue by MiChongs** [SherlockGougou/BigImageViewPager#186]
今天发现了作者你的框架在coloros 13上保存图片一直显示拒绝了存储权限，经过测试之后，coloros13已经砍掉了WRITE_EXTERNAL_STORAGE和READ_EXTERNAL_STORAGE这两个权限，使用getActivity大佬的XXPermisson框架在coloros 13上申请存储权限也无果，没有任何权限申请弹窗，所以我就找了另一个针对于Android10以上保存图片无需存储权限的方法，详见https://juejin.cn/post/7042218651482587172

**Comment by SherlockGougou** [comment]
感谢反馈！我周末抽时间修复一下。

Hayers ***@***.***>于2023年2月10日 周五20:19写道：

**Comment by SherlockGougou** [comment]
![1](https://user-images.githubusercontent.com/17920617/218309811-4d8b5a01-25a1-4fe8-a8b8-7139be6fd0d3.jpg)
![2](https://user-images.githubusercontent.com/17920617/218309816-e9d92c65-dc03-4e1b-9f6c-d2d3963445f4.jpg)
![3](https://user-images.githubusercontent.com/17920617/218309818-b58ff285-f6ee-430d-bafc-2084ae013a9e.jpg)
![4](https://user-images.githubusercontent.com/17920617/218309819-d35ddfbb-1ccc-4987-b65d-8b8744d74c23.jpg)
![5](https://user-images.githubusercontent.com/17920617/218309821-243f6e4d-f1dd-4574-bebf-9309ff4f3c17.jpg)
![6](https://user-images.githubusercontent.com/17920617/218309822-99b4465d-1882-4b0d-8473-b926f1657b26.jpg)

**Comment by SherlockGougou** [comment]
我使用OPPO的最新机型（Android 13 + ColorOS 13）Reno9 Pro(PGX110)，测试发现一切正常呢。具体看上面截图，一步步的操作。

**Comment by SherlockGougou** [comment]
没有得到你的回复，这个issue我暂时先关闭了，有问题可以再回复。
