### ISSUE TITLE
保存图片toast

### ISSUE THREAD

**Issue by Lancerer** [SherlockGougou/BigImageViewPager#187]
关闭保存图片成功的toast可否提供接口自定义显示或者不显示？

**Comment by SherlockGougou** [comment]
可 晚上加

Lancerer ***@***.***>于2023年2月28日 周二19:47写道：

**Comment by Lancerer** [comment]
老哥，现在还有一种特殊的情况，就是实际上是gif但是他的后缀名变成了jpg，这时候点击放大查看的时候好像图片会加载不出来，一直处于loading状态

**Comment by SherlockGougou** [comment]
你可以知道每一张图片的真实格式吗？

Lancerer ***@***.***>于2023年2月28日 周二19:58写道：

**Comment by SherlockGougou** [comment]
> 老哥，现在还有一种特殊的情况，就是实际上是gif但是他的后缀名变成了jpg，这时候点击放大查看的时候好像图片会加载不出来，一直处于loading状态

这种情况，可以提供一组url吗？

**Comment by SherlockGougou** [comment]
```
// 下载过程回调，可自定义toast，如果不设置此回调会使用默认的toast内容
.setDownloadListener(new OnDownloadListener() {
    @Override
    public void onDownloadStart(Activity activity, int position) {
        Toast.makeText(activity, "开始下载", Toast.LENGTH_SHORT).show();
    }

    @Override
    public void onDownloadSuccess(Activity activity, int position) {
        Toast.makeText(activity, "下载成功", Toast.LENGTH_SHORT).show();
    }

    @Override
    public void onDownloadFailed(Activity activity, int position) {
        Toast.makeText(activity, "下载失败", Toast.LENGTH_SHORT).show();
    }
})
```
接下来发布的版本增加了toast的自定义接口，按照上述方式即可。

**Comment by SherlockGougou** [comment]
androidx-7.1.5 已发布。

**Comment by Lancerer** [comment]
> > 老哥，现在还有一种特殊的情况，就是实际上是gif但是他的后缀名变成了jpg，这时候点击放大查看的时候好像图片会加载不出来，一直处于loading状态
> 
> 这种情况，可以提供一组url吗？

你可以用它测试一下 https://oss.xinyuhole.com/emoji/2023-02/02/10162466da129f5be82f5881e3c22fb88da2f5d0.jpg

**Comment by SherlockGougou** [comment]
androidx-7.1.6 修复了，可以试一下。

**Comment by Lancerer** [comment]
> androidx-7.1.6 修复了，可以试一下。

OK了，迅速啊老哥
