### ISSUE TITLE
三星手机虚拟按键与下载按钮适配

### ISSUE THREAD

**Issue by LeonShannon** [SherlockGougou/BigImageViewPager#188]
![img_v2_290431a3-b2f0-4e28-8dd4-06d927b18a9g](https://user-images.githubusercontent.com/24221796/227098959-14db9d7e-4f10-45fb-a161-e2ef960b2261.jpg)

**Comment by SherlockGougou** [comment]
你可以使用自定义布局实现，详情看一下demo中的示例。
