### ISSUE TITLE
安卓13下载图片提示没有存储权限

### ISSUE THREAD

**Issue by yang-jiacheng** [SherlockGougou/BigImageViewPager#189]
啥时候适配安卓13啊哥，安卓13即使我给了存储权限，点击下载还是会提示没有打开存储权限，建议一下把下载路径改成context.getExternalFilesDir(null).getAbsolutePath()这个路径，Picture路径无法写出存储哎

**Comment by SherlockGougou** [comment]
7.2.1试试呢。

**Comment by SherlockGougou** [comment]
最新7.2.3，如果有问题再回复。
