### ISSUE TITLE
HEIC加载失败

### ISSUE THREAD

**Issue by LeonShannon** [SherlockGougou/BigImageViewPager#190]
SDK版本：7.2.2
Android版本：Android13
手机型号：vivo V1955A
出错URL：https://switch-cdn.vgjump.com/Android_1681181317625_d2959134-f14b-4b7b-9f41-5c08fb72c4cb

使用ImageUtil.getImageTypeWithMime，得到的结果是heif。我用自己的glide是可以加载出来的，但是点击查看大图就不行了，图就裂开了

**Comment by SherlockGougou** [comment]
这张图片我在Chrome也打不开呢，显示一个小白块。

**Comment by SherlockGougou** [comment]
你的原图和缩略图的url分别是什么？我模拟看一下

**Comment by SherlockGougou** [comment]
大概看到原因了，我这边修复一下。稍等几分钟。

**Comment by SherlockGougou** [comment]
7.2.3修复了，可以再试一下，要稍等几分钟，jitpack还在编译中。

**Comment by SherlockGougou** [comment]
已经编译完成，如果 有问题再回复。
