### ISSUE TITLE
下载图片权限申请

### ISSUE THREAD

**Issue by Lancerer** [SherlockGougou/BigImageViewPager#192]
你好，关于下载按钮点击事件的权限申请，是不是应该不管我们自定义了下载事件，还是使用您的下载方法，都应该在这之前执行权限申请？，不然我这边如果自定义了下载事件，申请权限后无法重写onRequestPermissionsResult方法，进行下一步操作

**Comment by SherlockGougou** [comment]
你好，如果使用的是默认的下载行为，SDK内部已经做了权限申请了，无需再处理；但如果你自定义了下载行为，需要你事先申请权限。

**Comment by SherlockGougou** [comment]
下载拦截仅仅是将事件暴露出来，后续的所有逻辑需要自行处理。

**Comment by Lancerer** [comment]
> 下载拦截仅仅是将事件暴露出来，后续的所有逻辑需要自行处理。

好的
