### ISSUE TITLE
查看原图，图片预览叠加

### ISSUE THREAD

**Issue by zjclugger** [SherlockGougou/BigImageViewPager#193]
当预览图片列表时，点击查看原图
1.快速切换下一张同样点击查看原因
2.重复操作1多次
等图片下载完成后出现图片叠加的问题
![image](https://github.com/SherlockGougou/BigImageViewPager/assets/5424782/fdc3cc1f-2f84-4692-904b-2c1bbad66f3b)

![image](https://github.com/SherlockGougou/BigImageViewPager/assets/5424782/8f8166a1-3e06-4a74-96ef-2419d8b1c216)

**Comment by zjclugger** [comment]
以上两个问题是在下载源码在本地运行后遇到的，如果直接maven引用点击【查看原图】会一直显示0%或1%

**Comment by SherlockGougou** [comment]
ok，感谢反馈。我这边看一下。
