### ISSUE TITLE
有没有自定义布局隐藏显示效果实现方法?

### ISSUE THREAD

**Issue by kuitao1018** [SherlockGougou/BigImageViewPager#197]
作者你好,自定义布局后,怎么把我加入的布局,在图片拖拽时,和依赖布局一样有隐藏显示效果?

**Comment by SherlockGougou** [comment]
提供一下你的自定义布局代码呢，我这边看看。

**Comment by kuitao1018** [comment]
<?xml version="1.0" encoding="utf-8"?>
<layout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tootls="http://schemas.android.com/tools">

    <data>

    </data>

    <androidx.constraintlayout.widget.ConstraintLayout
        android:id="@+id/rootView"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:background="@color/black"
        android:paddingTop="28dp">

        <cc.shinichi.library.view.HackyViewPager
            android:id="@+id/viewPager"
            android:layout_width="match_parent"
            android:layout_height="match_parent" />

        <com.btpj.lib_base.widgets.TitleLayout
            android:id="@+id/titleLayout"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            app:isShowBack="false"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintTop_toTopOf="parent" />

        <FrameLayout
            android:id="@+id/fm_center_progress_container"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_centerInParent="true"
            app:layout_constraintBottom_toBottomOf="parent"
            app:layout_constraintEnd_toEndOf="parent"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintTop_toTopOf="parent">

        </FrameLayout>

        <TextView
            android:id="@+id/tv_indicator"
            android:layout_width="wrap_content"
            android:layout_height="20dp"
            android:layout_alignParentTop="true"
            android:layout_centerHorizontal="true"
            android:background="@drawable/shape_indicator_bg"
            android:gravity="center"
            android:includeFontPadding="false"
            android:text="1/9"
            android:textColor="#ffffff"
            android:textSize="15sp"
            app:layout_constraintBottom_toBottomOf="@+id/titleLayout"
            app:layout_constraintEnd_toEndOf="parent"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintTop_toTopOf="@+id/titleLayout" />

        <ImageView
            android:id="@+id/imgCloseButton"
            android:layout_width="60dp"
            android:layout_height="60dp"
            android:layout_alignParentStart="true"
            android:layout_alignParentBottom="true"
            android:layout_gravity="bottom|start"
            android:layout_marginBottom="40dp"
            android:padding="3dp"
            android:scaleType="centerInside"
            android:visibility="gone"
            app:layout_constraintBottom_toBottomOf="parent"
            app:layout_constraintStart_toStartOf="parent"
            app:srcCompat="@drawable/ic_action_close" />

        <FrameLayout
            android:id="@+id/fm_image_show_origin_container"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_alignParentBottom="true"
            android:layout_centerHorizontal="true"
            android:layout_marginBottom="40dp"
            android:visibility="gone"
            app:layout_constraintBottom_toBottomOf="parent"
            app:layout_constraintEnd_toEndOf="parent"
            app:layout_constraintStart_toStartOf="parent">

            <Button
                android:id="@+id/btn_show_origin"
                android:layout_width="wrap_content"
                android:layout_height="35dp"
                android:background="@drawable/gray_square_circle_bg_white_stroke"
                android:gravity="center"
                android:includeFontPadding="false"
                android:paddingHorizontal="10dp"
                android:text="@string/btn_original"
                android:textAllCaps="false"
                android:textColor="#ffffff"
                android:textSize="12sp" />
        </FrameLayout>

        <ImageView
            android:id="@+id/img_download"
            android:layout_width="60dp"
            android:layout_height="60dp"
            android:layout_alignParentEnd="true"
            android:layout_alignParentBottom="true"
            android:layout_gravity="bottom|end"
            android:layout_marginBottom="40dp"
            android:padding="3dp"
            android:scaleType="centerInside"
            android:visibility="gone"
            app:layout_constraintBottom_toBottomOf="parent"
            app:layout_constraintEnd_toEndOf="parent"
            app:srcCompat="@drawable/icon_download_new" />

        
        <androidx.constraintlayout.widget.ConstraintLayout
            android:id="@+id/cl_user"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_marginStart="16dp"
            android:layout_marginEnd="11dp"
            android:layout_marginBottom="46dp"
            android:visibility="gone"
            app:layout_constraintBottom_toBottomOf="parent"
            app:layout_constraintEnd_toEndOf="parent"
            app:layout_constraintStart_toStartOf="parent">

            <de.hdodenhof.circleimageview.CircleImageView
                android:id="@+id/civ_user"
                android:layout_width="42dp"
                android:layout_height="42dp"
                app:civ_border_color="@color/gray"
                app:civ_border_width="1dp"
                app:layout_constraintStart_toStartOf="parent"
                app:layout_constraintTop_toTopOf="parent" />


            <TextView
                android:id="@+id/tv_name"
                android:layout_width="0dp"
                android:layout_height="wrap_content"
                android:layout_marginStart="10dp"
                android:layout_marginEnd="8dp"
                android:textColor="@color/white"
                android:textSize="16sp"
                app:layout_constraintBottom_toBottomOf="@+id/civ_user"
                app:layout_constraintEnd_toStartOf="@+id/tv_to_details"
                app:layout_constraintStart_toEndOf="@+id/civ_user"
                app:layout_constraintTop_toTopOf="@+id/civ_user"
                tootls:text="122313" />


            <TextView
                android:id="@+id/tv_content"
                android:layout_width="0dp"
                android:layout_height="wrap_content"
                android:layout_marginTop="8dp"
                android:layout_marginEnd="8dp"
                android:ellipsize="end"
                android:maxLines="2"
                android:textColor="@color/white"
                android:textSize="14sp"
                app:layout_constraintBottom_toBottomOf="parent"
                app:layout_constraintEnd_toStartOf="@+id/tv_to_details"
                app:layout_constraintStart_toStartOf="parent"
                app:layout_constraintTop_toBottomOf="@+id/civ_user"
                tootls:text="122313" />

            <TextView
                android:id="@+id/tv_to_details"
                android:layout_width="wrap_content"
                android:layout_height="match_parent"
                android:padding="5dp"
                android:text="详情"
                android:textColor="@color/bg_bb"
                app:drawableEndCompat="@mipmap/ic_product_right"
                app:layout_constraintBottom_toBottomOf="parent"
                app:layout_constraintEnd_toEndOf="parent"
                app:layout_constraintTop_toTopOf="parent" />

        </androidx.constraintlayout.widget.ConstraintLayout>


    </androidx.constraintlayout.widget.ConstraintLayout>
</layout>

> 提供一下你的自定义布局代码呢，我这边看看。
