### ISSUE TITLE
  java.lang.IllegalArgumentException: Software rendering doesn't support hardware bitmaps

### ISSUE THREAD

**Issue by minorlai** [SherlockGougou/BigImageViewPager#198]
ImagePreview.instance
            .setContext(context)
            .setImage(imgUrl!!)
            // 加载策略，默认为手动模式
            .setLoadStrategy(LoadStrategy.Default)
            // 长图的展示模式，默认是SCALE_TYPE_CENTER_INSIDE，缩小到内部居中：
            .setLongPicDisplayMode(ImagePreview.LongPicDisplayMode.FillWidth)
            // 保存的文件夹名称，会在Picture目录进行文件夹的新建。比如："BigImageView"，会在Picture目录新建BigImageView文件夹)
            .setFolderName("imgPreview")
            // 是否启用点击图片关闭。默认启用
            .setEnableClickClose(true)
            // 是否启用下拉关闭。默认不启用
            .setEnableDragClose(true)
            // 是否忽略缩放启用拉动关闭。默认不忽略
            .setEnableDragCloseIgnoreScale(true)
            // 是否启用上拉关闭。默认不启用
            .setEnableUpDragClose(true)
            .setTransitionView(currentView)
            .setTransitionShareElementName("shared_element_container")
            .start()

**Comment by minorlai** [comment]
设置了这两个就会报错
.setTransitionView(currentView)
.setTransitionShareElementName("shared_element_container")

**Comment by minorlai** [comment]
@equationl @BzCoder @lovexyx @SherlockGougou 
麻烦看一下

**Comment by SherlockGougou** [comment]
好的👌下午看一下

**Comment by SherlockGougou** [comment]
你好，我测试发现没有问题呢。你拉一下项目，运行一下demo看看是否正常。

**Comment by SherlockGougou** [comment]
或者提供你下你那边可复现的最小化工程代码。

**Comment by minorlai** [comment]
你好，解决了，是因为没有加上 setZoomTransitionDuration 属性
缩放关闭后，页面上的图片会闪一下是什么原因呢

**Comment by SherlockGougou** [comment]
共享元素动画支持已去除。
