### ISSUE TITLE
加载本地图片出错。

### ISSUE THREAD

**Issue by chunwhite** [SherlockGougou/BigImageViewPager#199]
每次进程启动，只有第一次可以显示本地图片，第二次无法显示

**Comment by SherlockGougou** [comment]
你好，可以提供一下录屏吗？

chunwhite ***@***.***>于2024年2月18日 周日10:21写道：

**Comment by dongtianlong** [comment]
![error](https://github.com/SherlockGougou/BigImageViewPager/assets/21264012/c9eff747-7188-4022-9007-68dea28bc1f4)
同样出现该问题，图片为出现该问题的异常log
