### ISSUE TITLE
NoSuchMethodError

### ISSUE THREAD

**Issue by as11051105** [SherlockGougou/BigImageViewPager#2]
glide 4.5 

  java.lang.NoSuchMethodError: No direct method <init>(I)V in class Lcom/bumptech/glide/util/LruCache; or its super classes (declaration of 'com.bumptech.glide.util.LruCache' appears in /data/app/com.cmiot.logisticswarehouse-ZGK19cyE4HzT7HFVl7U9rw==/split_lib_dependencies_apk.apk)

**Comment by SherlockGougou** [comment]
抱歉，目前仅支持glide 3.x，后期会加入4.x的支持。

**Comment by SherlockGougou** [comment]
您好，我已经对框架进行更新，已支持glide 4.x，最新版本是v1.1.1，您可以试一下。
