### ISSUE TITLE
保存图片能添加水印吗

### ISSUE THREAD

**Issue by fumayer** [SherlockGougou/BigImageViewPager#202]
大佬，保存图片能添加水印吗，自己能扩展吗，从哪入手呢

**Comment by SherlockGougou** [comment]
文档有提到自己实现下载功能的，你可以自己实现下载后，再合并bitmap达到目的。

**Comment by SherlockGougou** [comment]
```setDownloadClickListener```这个方法，你传入回调，内部就不会下载了。
