### ISSUE TITLE
建议在ImagePreview添加WeakReference<Context> wr，弱引用上下文，因为单例容易造成内存泄露

### ISSUE THREAD

**Issue by dary123** [SherlockGougou/BigImageViewPager#23]
建议在ImagePreview添加WeakReference<Context> wr，弱引用上下文，因为单例容易造成内存泄露

**Comment by SherlockGougou** [comment]
代码中已经在适当的位置对context的引用进行置空，不会造成内存泄漏。传入的context仅仅用作跳转activity，没有长周期的持有；在看大图页面结束时，就对context进行了置空。你可以进行频繁的跳转测试，看有没有内存泄漏。不过，最优的正确写法还是使用弱引用，3.2.2已经改为弱引用了，感谢建议。
