### ISSUE TITLE
作者大大你好，我想问下加载的百分比可以获取到吗，因为我想加上加载时显示百分比

### ISSUE THREAD

**Issue by dary123** [SherlockGougou/BigImageViewPager#26]
作者大大你好，我想问下加载的百分比可以获取到吗，因为我想加上加载时显示百分比

**Comment by SherlockGougou** [comment]
你说的是缩略图的加载百分比嘛？加载原图时的百分比是有的，但是没有暴露出来。

**Comment by dary123** [comment]
我说的是原图的百分比，因为公司有需求，需要加载原图时不是显示进度条，而是显示百分比

**Comment by SherlockGougou** [comment]
你可以复制源码后，自己改写这个类中的相应代码：[https://github.com/SherlockGougou/BigImageViewPager/blob/master/library/src/main/java/cc/shinichi/library/view/ImagePreviewActivity.java](url) 显示百分比的代码在这一块：
![image](https://user-images.githubusercontent.com/17920617/51012076-52351900-1596-11e9-99ee-b28c79f41b07.png)

后续有空可能会提供自定义百分比View的功能。

**Comment by dary123** [comment]
好的，感谢

**Comment by SherlockGougou** [comment]
最新版本的4.0.0已经支持自定义百分比了，详情可以看Demo：https://github.com/SherlockGougou/BigImageViewPager/blob/master/sample/src/main/java/cc/shinichi/bigimageviewpager/MainActivity.java#L291
