### ISSUE TITLE
显示大图的时候，因为RequestListener部分导致崩溃，请问这个怎么解决

### ISSUE THREAD

**Issue by zzq5636243** [SherlockGougou/BigImageViewPager#27]
No virtual method addListener(Lcom/bumptech/glide/request/RequestListener;)Lcom/bumptech/glide/RequestBuilder; in class Lcom/bumptech/glide/RequestBuilder; or its super classes (declaration of 'com.bumptech.glide.RequestBuilder' appears in /data/app/com.emotte.jzc-1/base.apk:classes3.dex)

**Comment by SherlockGougou** [comment]
请先确认一下自己的glide版本是否是4.8.0，如果不是，改成4.8.0后再试试。

**Comment by SherlockGougou** [comment]
请问还有问题吗？我先关了这个issue，有问题你可以再提。
