### ISSUE TITLE
手势已经很不错了，建议：可以添加一个图片列表，增加过度动画，类似朋友圈打开和关闭的过度动画效果

### ISSUE THREAD

**Issue by Ramblerchris** [SherlockGougou/BigImageViewPager#28]

**Comment by SherlockGougou** [comment]
感谢建议，动画之类的都在开发队列中，有空了都会加。

**Comment by petma** [comment]
同需求

**Comment by petma** [comment]
可以尝试  
ActivityOptionsCompat compat =
                ActivityOptionsCompat.makeSceneTransitionAnimation(this,
                        view, "img")
我成功了

**Comment by wangtao2855** [comment]
> 可以尝试
> ActivityOptionsCompat compat =
> ActivityOptionsCompat.makeSceneTransitionAnimation(this,
> view, "img")
> 我成功了

哥 你是咋做的 方便发我看看吗?

**Comment by NeVaDaAAA** [comment]
加入过度动画这个库就完美了

**Comment by SherlockGougou** [comment]
后续会支持模拟的共享元素动画。
