### ISSUE TITLE
com.android.support:appcompat-v728.0.0报错

### ISSUE THREAD

**Issue by YangPeiru** [SherlockGougou/BigImageViewPager#30]
<item name="sh_progress_text" type="id">false</item>
    <item name="sh_progress_view" type="id">false</item>
28以后只能这样写
 ` <item name="sh_progress_text" type="id"/>`
    `<item name="sh_progress_view" type="id"/>`

**Comment by YangPeiru** [comment]
<item name="sh_progress_text" type="id"/>
    <item name="sh_progress_view" type="id"/>

**Comment by SherlockGougou** [comment]
感谢反馈！稍后更新一下。
