### ISSUE TITLE
是否支持自定义预览页面布局

### ISSUE THREAD

**Issue by suzhonxia** [SherlockGougou/BigImageViewPager#32]
在不修改源码的情况下是否支持自定义预览页面布局结构，比如说左上角返回键，右上角功能按钮，底部增加文本显示等。

**Comment by SherlockGougou** [comment]
暂不支持，以后会添加

**Comment by SherlockGougou** [comment]
如果想完全自定义，可以试着clone代码，以module的形式依赖，布局更改随心所欲。
