### ISSUE TITLE
目前这个库跟androidx一起用会报错

### ISSUE THREAD

**Issue by dary123** [SherlockGougou/BigImageViewPager#33]
![_20190306133439](https://user-images.githubusercontent.com/12826258/53858351-cb8c3d80-4014-11e9-8b46-f8f24181dcef.png)
目前这个库跟androidx一起用会报错

**Comment by SherlockGougou** [comment]
你好，目前暂未支持androidx，后续会单独出一个分支。

**Comment by dary123** [comment]
恩恩，没事，我发现把androidx.exifinterface:exifinterface:1.0.0改为androidx.exifinterface:exifinterface:1.0.0-rc01降低一下版本就可以正常使用了，好像不会产生任何冲突
