### ISSUE TITLE
使用发生崩溃

### ISSUE THREAD

**Issue by gjmm123** [SherlockGougou/BigImageViewPager#37]
使用发生崩溃
点击操作调用    ImagePreview.getInstance()
                        .setContext(CloudPhotoDetailsActivity.this)
//                        .setIndex(0)
//                        .setImageList(list)                       .setImage("https://ss3.bdstatic.com/70cFv8Sh_Q1YnxGkpoWK1HF6hhy/it/u=1986179278,1118313821&fm=27&gp=0.jpg")
                        .start();
然后就发生崩溃 图片不能显示

![QQ图片20190312170348](https://user-images.githubusercontent.com/48173775/54187584-e36a3280-44e8-11e9-8465-a4b276a8e124.png)

**Comment by SherlockGougou** [comment]
在你的app的build.gradle依赖中，添加以下：
 ```
 implementation 'com.android.support:exifinterface:28.0.0'
```

**Comment by gjmm123** [comment]
大佬，崩溃没有了，可以展示图片了，不过我展示手机相册图片，因为拍摄的图片很大，有2M多一张，结果就滑动时非常卡顿，这有办法处理吗

**Comment by SherlockGougou** [comment]
好的，我测试一下

**Comment by gjmm123** [comment]
大佬，我换了个性能好点的手机不算很卡，用华为麦芒4卡的要死，我想压缩图片用这个控件展示，有没有方法呀

**Comment by SherlockGougou** [comment]
本框架的设计初衷就是尽量保证质量的显示大图和长图，如果需要压缩显示，可能这个框架不是很适合你的需求。不过，可能后期会加入有损显示的特性，以保证加载速度。
