### ISSUE TITLE
上拉不能关闭大图

### ISSUE THREAD

**Issue by gjmm123** [SherlockGougou/BigImageViewPager#38]
打开大图，上拉不能关闭，会弹回来，下拉可以

**Comment by SherlockGougou** [comment]
这个是这么设计的，目前未提供更改的接口，你可以通过更改这里来实现双向关闭：
https://github.com/SherlockGougou/BigImageViewPager/blob/master/library/src/main/java/cc/shinichi/library/view/helper/FingerDragHelper.java#L125

其中注释掉的就是双向关闭的代码。

**Comment by gjmm123** [comment]
好的，谢谢
