### ISSUE TITLE
huaweid手机大图显示不全

### ISSUE THREAD

**Issue by nellace** [SherlockGougou/BigImageViewPager#46]
https://ws1.sinaimg.cn/large/686c6057ly1g2cltzs406j20f00qoab2.jpg

上面的页码text和关闭按钮显示不出来

**Comment by nellace** [comment]
情况出现在下面软键盘出现的时候

**Comment by SherlockGougou** [comment]
请问demo有问题吗？

**Comment by nellace** [comment]
> 请问demo有问题吗？

对 demo也有，华为荣耀6plus，图片url：http://api.souips.com:8080/hpic/FMZL/2014/20140219/E2/636E7479B37CA18B5304B9C7B230F5/000003.PNG

**Comment by SherlockGougou** [comment]
这是因为图片是白色的 关闭按钮那些图片也是白色的，重了就看不到了，你可以自定义那些图片的资源，改用白色带深色背景的图片。
