### ISSUE TITLE
建议可以禁用缓存

### ISSUE THREAD

**Issue by equationl** [SherlockGougou/BigImageViewPager#51]
当使用来自同一来源的图片时，会被Glide自动缓存，但是这个来源的图片经常改变，而Glide的缓存并不会更新，以前用过一个框架就可以禁用缓存，不过那个框架无法查看超大图，所以转成了作者现在的这个框架，希望作者能考虑一下我的建议

**Comment by SherlockGougou** [comment]
你的意思是说，图片的url是一样的，但是图片不一样，就类似头像那种吗？是需要提供一个禁用缓存的方法？

**Comment by equationl** [comment]
对，类似头像的需求，不过我的需求可能更加激进，因为每次打开图片预览图片都会变，但是url是一样的

**Comment by SherlockGougou** [comment]
那你可以先试试 每次加载url时，在url后面拼接一个```?时间戳```，让glide认为不是同一个图片，可以先暂时这么做。我最近比较忙，抱歉。你也可以修改代码后提PR。

**Comment by equationl** [comment]
哈哈，这个有想到，不过需求比较特殊，并不是网络图片，而是本地图片，而且暂时无法通过改文件名来避免缓存。
我再想想其他解决方案吧，感谢作者
