### ISSUE TITLE
图片加载失败的提示，可否增加开关不提示

### ISSUE THREAD

**Issue by zhuoshirong** [SherlockGougou/BigImageViewPager#54]

**Comment by SherlockGougou** [comment]
不好意思，最近太忙了。你可以拉取下来后作为module依赖，更改这行代码来实现：
https://github.com/SherlockGougou/BigImageViewPager/blob/master/library/src/main/java/cc/shinichi/library/view/ImagePreviewAdapter.java#L396

**Comment by zhuoshirong** [comment]
已修改
