### ISSUE TITLE
我的图片加载出来少了好多东西

### ISSUE THREAD

**Issue by baoyu1990** [SherlockGougou/BigImageViewPager#55]
http://hongdan24.oss-cn-qingdao.aliyuncs.com/nba/9071185e93c349518d43a39b3281d99f.png?Expires=4714034889&OSSAccessKeyId=LTAIKcJlkph5LwgI&Signature=3aSgfpyknDCb8u8E8nrsSGTrSws%3D图片地址 上面的文字加载出来 都没有了

**Comment by SherlockGougou** [comment]
我看这个图的文字是黑色的，是不是因为背景也是黑色的导致看不到了？你可以下载一下 去图库看看有木有文字

**Comment by baoyu1990** [comment]
哎呀 好激动 好激动  谢谢您 项目明天上线  刚测试出来这个问题    这个图片本身是有个白色背景的 （白色背景上才是这个文字和图片）




------------------ 原始邮件 ------------------
发件人: "工藤一号"<notifications@github.com>; 
发送时间: 2019年6月13日(星期四) 晚上10:44
收件人: "SherlockGougou/BigImageViewPager"<BigImageViewPager@noreply.github.com>; 
抄送: "境花水月"<1346561287@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [SherlockGougou/BigImageViewPager] 我的图片加载出来少了好多东西 (#55)




我看这个图的文字是黑色的，是不是因为背景也是黑色的导致看不到了？你可以下载一下 去图库看看有木有文字

**Comment by SherlockGougou** [comment]
我会增加一个接口，可以设置全屏的背景色。请问你使用的是v4还是v3？

**Comment by baoyu1990** [comment]
我使用的是v3




------------------ 原始邮件 ------------------
发件人: "工藤一号"<notifications@github.com>; 
发送时间: 2019年6月13日(星期四) 晚上10:48
收件人: "SherlockGougou/BigImageViewPager"<BigImageViewPager@noreply.github.com>; 
抄送: "境花水月"<1346561287@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [SherlockGougou/BigImageViewPager] 我的图片加载出来少了好多东西 (#55)




我会增加一个接口，可以设置全屏的背景色。请问你使用的是v4还是v3？

**Comment by SherlockGougou** [comment]
我尝试了一下，不是很好解决这种问题，如果背景设置为白色的话，要处理下拉时背景的透明度变化，还要处理状态栏字体的颜色。所以，如果你需要解决这个问题的话，可以下载v3的源码，更改以下两处代码，强制把背景设置为白色的，但是我不建议处理这个问题，因为可以从更改图片背景解决。


![image](https://user-images.githubusercontent.com/17920617/59446937-0c29fd00-8e35-11e9-957b-5115b9890df4.png)

![image](https://user-images.githubusercontent.com/17920617/59446989-2237bd80-8e35-11e9-852e-9403bdf40bdd.png)

**Comment by baoyu1990** [comment]
我们的图片 数据 是从国外网站抓取的数据  没法修改




------------------ 原始邮件 ------------------
发件人: "工藤一号"<notifications@github.com>; 
发送时间: 2019年6月13日(星期四) 晚上11:44
收件人: "SherlockGougou/BigImageViewPager"<BigImageViewPager@noreply.github.com>; 
抄送: "境花水月"<1346561287@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [SherlockGougou/BigImageViewPager] 我的图片加载出来少了好多东西 (#55)




我尝试了一下，不是很好解决这种问题，如果背景设置为白色的话，要处理下拉时背景的透明度变化，还要处理状态栏字体的颜色。所以，如果你需要解决这个问题的话，可以下载v3的源码，更改以下两处代码，强制把背景设置为白色的，但是我不建议处理这个问题，因为可以从更改图片背景解决。
