### ISSUE TITLE
android:windowIsTranslucent=true 会有问题

### ISSUE THREAD

**Issue by Yang4an** [SherlockGougou/BigImageViewPager#56]
android:windowIsTranslucent=true  在华为8.0上会出现问题，需要适配？

**Comment by SherlockGougou** [comment]
请问你是加到哪里的？具体问题可以截个图嘛？

**Comment by zhangnin** [comment]
> android:windowIsTranslucent=true 在华为8.0上会出现问题，需要适配？

8.0系统有一个bug，你需要修改下AndroidManifest，activity设置透明，不能固定屏幕方向。
去掉 android:screenOrientation="portrait"

**Comment by SherlockGougou** [comment]
经测试，未发现有问题。
