### ISSUE TITLE
仅加载原图模式下无法修改ProgressBar样式

### ISSUE THREAD

**Issue by jianjunzhao-github** [SherlockGougou/BigImageViewPager#57]
仅加载原图的模式下，没有办法修改你的默认ProgressBar样式，就是你的sh_item_photoview.xml -> progress_view ，我想修改下大小和颜色该如何处理？能提供个方法吗

**Comment by SherlockGougou** [comment]
如果提供的方法不满足你的需求，建议你下载源码作为module进行依赖，任意样式都可以更改。
