### ISSUE TITLE
浏览图片出现了个bug

### ISSUE THREAD

**Issue by meijingkang** [SherlockGougou/BigImageViewPager#6]
浏览图片,左右滑动偶尔会有bug,

![screenshot_2018-10-31-16-20-26-198_com miui bugre](https://user-images.githubusercontent.com/15361537/47775100-b7b09200-dd29-11e8-8585-ed7779bfa223.png)
另外,我发现有时候不响应下拉图片退出的手势

**Comment by SherlockGougou** [comment]
请问这个问题你是解决了还是怎么回事？怎么关闭了issue？

**Comment by jemon9** [comment]
我也遇到了同样的问题，但是还没有什么解决方案，请问你最终怎么解决的？

**Comment by meijingkang** [comment]
我看了下源码,发现是我自己的问题,在给bigimageviewpager传递图片源的时候,

1. 传的集合有可能为空
2.index下标超过了集合长度

bigimageviewpager未做检查,我们要自己提前处理
<img width="1337" alt="qq20181207-115108 2x" src="https://user-images.githubusercontent.com/15361537/49627447-d76a6280-fa19-11e8-8849-487c834122dd.png">

希望能帮到你们
