### ISSUE TITLE
作为弹出框效果，怎样处理与activity中重写的backpress方法的冲突

### ISSUE THREAD

**Issue by yunxingyu** [SherlockGougou/BigImageViewPager#63]
作为弹出框，怎样处理与activity的backpress方法的冲突，如首页有二次点击返回，但是，activity无法获取是否启动了查看图片弹框，导致必须点击两次才能关闭图片查看器页面。

**Comment by SherlockGougou** [comment]
应该不会有这种问题吧，显示图片时，首页的ac是onPause的呀。
