### ISSUE TITLE
希望支持AndroidX和自定义图片加载框架

### ISSUE THREAD

**Issue by oneapp1e** [SherlockGougou/BigImageViewPager#65]
希望支持AndroidX和自定义图片加载框架

**Comment by SherlockGougou** [comment]
1.androidx在计划中了；
2.自定义加载框架这个侵入性可能太高了，且有些图片加载框架不好实现加载百分比进度，所以暂时不打算提供此功能。

**Comment by SherlockGougou** [comment]
androidx现已支持，使用可查看readme。
