### ISSUE TITLE
内存占用达到1G以上了

### ISSUE THREAD

**Issue by WarriorYu** [SherlockGougou/BigImageViewPager#70]
非常感谢作者的库，但是使用中遇到内存占用过大的问题，有什么解决的办法吗？我的图片尺寸基本都是2000X3000px或者少部分5000X6000px的。希望给点建议
![image](https://user-images.githubusercontent.com/16720902/64086986-9cf5e200-cd6d-11e9-83e4-7988d3a3e6d8.png)

**Comment by SherlockGougou** [comment]
内存占用多少，需要看android的系统版本。在8.x以后，bitmap是以系统共享的方式加载进缓存里的，具体可以查相关资料。
