### ISSUE TITLE
百分比显示问题

### ISSUE THREAD

**Issue by liqy** [SherlockGougou/BigImageViewPager#73]
点击显示原图，百分比只加载到1%就不动了，回调方法失效

云心Demo好多图片显示错误，在浏览器中查看没有问题

**Comment by SherlockGougou** [comment]
glide版本是多少？建议4.8.0

**Comment by liqy** [comment]
就是4.8.0

**Comment by liqy** [comment]
现在是下载demo运行

**Comment by SherlockGougou** [comment]
有没有按照这一步设置呢？
![image](https://user-images.githubusercontent.com/17920617/67350904-bf8ec500-f57e-11e9-8726-629bbcfebf3f.png)

**Comment by SherlockGougou** [comment]
那麻烦看一下项目直接运行，加载失败有没有啥错误日志之类的。

**Comment by liqy** [comment]
内存泄漏

**Comment by liqy** [comment]
但是我导入包，直接运行没有问题，可以加载图片，就是百分比那块回调失败

**Comment by liqy** [comment]
回调监听那块

**Comment by chenjindiao** [comment]
这里应该是图片302了，然后进度显示那里回调的url和原图url不一致~

**Comment by SherlockGougou** [comment]
经过测试，demo是没有问题的。如果你还有其他问题，可以再提issue。
