### ISSUE TITLE
context must be a Activity!

### ISSUE THREAD

**Issue by TxcA** [SherlockGougou/BigImageViewPager#74]
extends Activity会报该错误，跟踪了一下，发现只能继承于 AppCompatActivity。
希望能兼容普通的Activity。

![issues.jpg](https://i.loli.net/2019/11/01/WerERukGFz1vlfg.jpg)

**Comment by SherlockGougou** [comment]
好的，感谢反馈！

**Comment by SherlockGougou** [comment]
androidx-5.0.3 已发布。
