### ISSUE TITLE
加载多张图片时，会出现黑屏现象

### ISSUE THREAD

**Issue by AnJiuZhe** [SherlockGougou/BigImageViewPager#75]
你好，某些图片加载出来，然后立刻就黑屏了，不知道啥原因。

**Comment by SherlockGougou** [comment]
请问Demo有问题吗？

**Comment by AnJiuZhe** [comment]
> 请问Demo有问题吗？

稍等。我测试一下

**Comment by SherlockGougou** [comment]
如果图片集合中有多张重复的图片，是会出现你描述的问题的。

**Comment by AnJiuZhe** [comment]
> 如果图片集合中有多张重复的图片，是会出现你描述的问题的。

没错，后台返回的图片地址确实有重复的。谢谢了
