### ISSUE TITLE
你好，请问支持bitmap格式吗？？？

### ISSUE THREAD

**Issue by yanghua0726** [SherlockGougou/BigImageViewPager#79]
我截图后获得了bitmap格式后想要显示，该如何做处理？？？

**Comment by SherlockGougou** [comment]
你好，bitmap是能直接支持的，如果需要显示bitmap，可以先将bitmap保存问本地文件，再使用本框架进行加载显示。

**Comment by yanghua0726** [comment]
好的谢谢，已解决。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"工藤一号"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月25日(星期一) 上午9:04
收件人:&nbsp;"SherlockGougou/BigImageViewPager"<BigImageViewPager@noreply.github.com&gt;;
抄送:&nbsp;"华"<1277231541@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [SherlockGougou/BigImageViewPager] 你好，请问支持bitmap格式吗？？？ (#79)




你好，bitmap是能直接支持的，如果需要显示bitmap，可以先将bitmap保存问本地文件，再使用本框架进行加载显示。
