### ISSUE TITLE
图片加载方向错误。

### ISSUE THREAD

**Issue by geekTaolipeng** [SherlockGougou/BigImageViewPager#8]
小米:mix2s
图片信息:4032x2016px
具体描述:图片在相册显示是竖向的，使用该库就变成了横向的。

**Comment by geekTaolipeng** [comment]
![4401541483831_ pic_hd](https://user-images.githubusercontent.com/43661320/48045625-08156d00-e1cc-11e8-8e12-2caccafe32a8.jpg)

**Comment by geekTaolipeng** [comment]
![4421541484106_ pic](https://user-images.githubusercontent.com/43661320/48045741-86720f00-e1cc-11e8-9e48-12303a4e017a.jpg)

**Comment by SherlockGougou** [comment]
感谢反馈，问题已经确认，解决后马上推新的版本。

**Comment by SherlockGougou** [comment]
最新版本：
v4_2.1.1
v3_2.1.1

麻烦再试试还有问题没。

**Comment by geekTaolipeng** [comment]
还是一样。
我已经上传原图。

**Comment by SherlockGougou** [comment]
再试试2.1.2呢

**Comment by geekTaolipeng** [comment]
好了,老哥 你响应速度太快了

**Comment by SherlockGougou** [comment]
ok，另外推荐你添加README中底部的那个QQ群，我们不是水群，互相学习交流。
