### ISSUE TITLE
关于图片放大逻辑

### ISSUE THREAD

**Issue by wadewen** [SherlockGougou/BigImageViewPager#81]
默认长图拉到屏幕宽度显示，会导致横屏应用体验不好，希望可以开放设置拉伸方向

**Comment by SherlockGougou** [comment]
good idea！

**Comment by FreshItFish** [comment]
我也碰到这个问题了，在平板应用中，横屏打开图片，看着有点尴尬，希望加上类似于ImageView的设置ScaleType的方式。

**Comment by jiangjiqing** [comment]
这个怎么设置那  亲

**Comment by w-double-w** [comment]
所以这个问题有解决方案了嘛

**Comment by hxkdidi** [comment]
if (isLongImage) {
            imageView.setMinimumScaleType(SubsamplingScaleImageViewDragClose.SCALE_TYPE_CENTER_INSIDE);
            imageView.setMinScale(ImageUtil.getLongImageMinScale(activity, imagePath));
            imageView.setMaxScale(ImageUtil.getLongImageMaxScale(activity, imagePath));
            imageView.setDoubleTapZoomScale(ImageUtil.getLongImageMaxScale(activity, imagePath));
        } else {
}即可

**Comment by SherlockGougou** [comment]
新版本优化了放大体验
