### ISSUE TITLE
是否可以考虑增加一个关闭方法？

### ISSUE THREAD

**Issue by equationl** [SherlockGougou/BigImageViewPager#84]
增加支持直接用代码控制退出图片浏览界面。

**Comment by SherlockGougou** [comment]
有什么具体的使用场景吗？我没想到有哪些场景需要这个。

**Comment by equationl** [comment]
@SherlockGougou 是这样的，因为我在图片查看界面的长按回调中加了一个删除当前图片的功能，如果删除图片后不退出图片浏览界面，则依然会以缓存继续显示。
我现在的解决方法是在删除图片后模拟点击返回按键来实现图片浏览
![Screenshot_20200228-121309_VideoShotPro](https://user-images.githubusercontent.com/6501123/75509785-c3968c00-5a23-11ea-98d5-58dc723f72b0.jpg)

**Comment by equationl** [comment]
5.0.6 在点击和长按回调中增加了上下文，可以直接调用上下文中的 onBackPressed() 或 finish() 实现

**Comment by SherlockGougou** [comment]
还有什么问题吗？

**Comment by equationl** [comment]
没问题了...手滑点错了，关闭了吧...
