### ISSUE TITLE
java.lang.IllegalStateException: GeneratedAppGlideModuleImpl is implemented incorrectly

### ISSUE THREAD

**Issue by LivedForward** [SherlockGougou/BigImageViewPager#85]
App启动时报如下错:
java.lang.IllegalStateException: GeneratedAppGlideModuleImpl is implemented incorrectly. If you've manually implemented this class, remove your implementation. The Annotation processor will generate a correct implementation.

Caused by: java.lang.NoSuchMethodException: <init> [class android.content.Context]

以下是Glide相关依赖:
 `implementation "com.github.bumptech.glide:glide:$glideVersion" `

` implementation ("com.github.bumptech.glide:recyclerview-integration:$glideVersion") {    
        transitive = false  
   // Excludes the support library because it's already included by Glide.
    }  `

    annotationProcessor "com.github.bumptech.glide:compiler:$glideVersion"  

    implementation "com.github.bumptech.glide:okhttp3-integration:$glideVersion"  

    implementation 'com.github.SherlockGougou:BigImageViewPager:androidx-5.0.4'

有自定义的AppGlideModule
glideVersion为4.9.0
无论是否添加这句:
` registry.replace(GlideUrl.class, InputStream.class, new OkHttpUrlLoader.Factory(ProgressManager.getOkHttpClient()));`

都会报错，但是注释掉BigImageViewPager:androidx-5.0.4这个依赖后，就可以正常启动。
使用的是androidx，而且没有开启代码混淆。

能帮忙看一下吗？

**Comment by LivedForward** [comment]
已解决，升级4.10

**Comment by andy19910618** [comment]
使用的com.github.SherlockGougou:BigImageViewPager:androidx-6.1.1 还是报这个错啊

**Comment by haoguibao** [comment]
> 已解决，升级4.10

现在引用implementation 'com.github.SherlockGougou:BigImageViewPager:androidx-6.1.5' ，同样报这个错，你用的没有问题吗？

**Comment by haoguibao** [comment]
> 使用的com.github.SherlockGougou:BigImageViewPager:androidx-6.1.1 还是报这个错啊

求教，现在解决了吗，怎么解决的？
