### ISSUE TITLE
加载原图时，有时候黑屏时间偏长，有没有解决方案？

### ISSUE THREAD

**Issue by wirteEable** [SherlockGougou/BigImageViewPager#86]

**Comment by SherlockGougou** [comment]
可以描述具体一些吗，比如提供录屏、图片地址、机型信息等。

**Comment by wirteEable** [comment]
![image](https://user-images.githubusercontent.com/13265455/75513379-a962ab00-5a2f-11ea-90b3-4ce9b5583c35.png)
![image](https://user-images.githubusercontent.com/13265455/75513370-a5cf2400-5a2f-11ea-83bd-af81170b3bb1.png)

**Comment by SherlockGougou** [comment]
如果有问题，可以再打开。
