### ISSUE TITLE
图片失真

### ISSUE THREAD

**Issue by 616852636** [SherlockGougou/BigImageViewPager#89]
点击查看图片后,图片严重失真 已经设置显示原图模式了, 我已经download项目library 
apply(new RequestOptions().format(DecodeFormat.PREFER_ARGB_8888).encodeQuality(100))也不行

**Comment by SherlockGougou** [comment]
发一下你的图片地址

**Comment by 616852636** [comment]
http://image.xiaobaiupin.com//upload//img//goods//20200215//6352dcadfc80dc654fb96746d88e7291.jpg

**Comment by 616852636** [comment]
点开后图片下半截会有失真现象,原图是没有的  谢谢您的解答

**Comment by SherlockGougou** [comment]
可以截图看一下你说的失真问题吗？

**Comment by 616852636** [comment]
![1584081538348](https://user-images.githubusercontent.com/14288334/76596254-a2ac5b80-6538-11ea-9721-b973ffdcb716.jpg)

**Comment by SherlockGougou** [comment]
不好意思，最近太忙了。这个问题其实不算是失真问题，是采样问题，只有纯色会有这个问题。
本框架图片采样使用的也是三方框架，目前处理不了这个问题。

**Comment by 616852636** [comment]
好的好的 感谢你的解答 我再仔细琢磨琢磨吧

**Comment by 616852636** [comment]
ImagePreviewAdapter 487 行
修改成:
ImageSource imageSource = ImageSource.bitmap(BitmapFactory.decodeFile(imagePath));
图片就清晰了
