### ISSUE TITLE
宽图显示异常，图片被顶到顶部，向下滑下才居中，而且特别宽的图没有整体一起显示，还需要右滑才能看到全部内容

### ISSUE THREAD

**Issue by dary123** [SherlockGougou/BigImageViewPager#9]
宽图显示异常，图片被顶到顶部，向下滑下才居中，而且特别宽的图没有整体一起显示，还需要右滑才能看到全部内容

**Comment by dary123** [comment]
好的，谢谢

**Comment by SherlockGougou** [comment]
你好这个问题已经修复，最新版本：
对于glide4.x : 使用v4_2.1.4
对于glide3.x : 使用v3_2.1.4
