### ISSUE TITLE
如何获取ImagePreviewActivity当前的上下文

### ISSUE THREAD

**Issue by dary123** [SherlockGougou/BigImageViewPager#92]
如何获取ImagePreviewActivity当前的上下文

**Comment by SherlockGougou** [comment]
先描述一下你的需求场景

**Comment by dary123** [comment]
我的需求场景是在ImagePreviewActivity当前页面跳转到一个新页面，需要用到转场动画，所以必须要有当前页面的上下文

**Comment by SherlockGougou** [comment]
你的跳转是如何触发的？

**Comment by dary123** [comment]
Intent intent = new Intent(AppManager.AppManager.currentActivity(), ShareMsgInfoFromFindActivity.class);
                                                            intent.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
                                                            AppManager.AppManager.currentActivity().startActivity(intent);
                                                            AppManager.AppManager.currentActivity().overridePendingTransition(R.anim.slide_in_up, R.anim.anim_hold);

**Comment by SherlockGougou** [comment]
你使用了：AppManager.AppManager.currentActivity()
应该没问题吧，你可以看一下AppManager.AppManager.currentActivity()获取的是不是ImagePreviewActivity。

**Comment by SherlockGougou** [comment]
如果获取的不是查看大图的activity，你可能需要更改一下Appmanager的实现。推荐使用ActivityLifecycleCallbacks进行监听当前activity。

**Comment by dary123** [comment]
AppManager.AppManager.currentActivity()获取到当前activity的前提是我必须要在AppManager.AppManager这个枚举里存储每一个打开activity，因为在ImagePreviewActivity没有add到存储的Activity栈里，所以currentActivity获取到的是上一个activity

**Comment by dary123** [comment]
ActivityLifecycleCallback会影响性能吗

**Comment by SherlockGougou** [comment]
建议你去了解一下ActivityLifecycleCallback。

**Comment by SherlockGougou** [comment]
建议不要使用addActivity的方式管理activity栈。

**Comment by dary123** [comment]
因为我之前用过ActivityLifecycleCallback，放在application里面，结果会导致App卡顿
