### ISSUE TITLE
downloadOnly加载原图的时候，经常出错

### ISSUE THREAD

**Issue by snakebang007** [SherlockGougou/BigImageViewPager#94]
按下加载原图后，downloadOnly执行后，okhttp反馈的进度已经完成，但是FileTarget却还是执行了onLoadFailed,实际上并没有生成缓存图片~研究了一天，不知道glide咋回事

**Comment by madreain** [comment]
我也遇到了加载原图失败的，有解决方法了吗

**Comment by liubingshopping** [comment]
我好像也遇到了，我是缓存的路径跟他，查询缓存的路径不一致造成的。
查询是context.getCacheDir() 
所以设置缓存路径只能是 builder.setDiskCache(new InternalCacheDiskCacheFactory(context));

**Comment by SherlockGougou** [comment]
新版本已经优化了。
