### ISSUE TITLE
Attempt to invoke virtual method 'boolean java.lang.String.equalsIgnoreCase(java.lang.String)' on a null object reference

### ISSUE THREAD

**Issue by huwencheng** [SherlockGougou/BigImageViewPager#96]
java.lang.RuntimeException:Unable to start activity ComponentInfo{com.yxsh.marriage/cc.shinichi.library.view.ImagePreviewActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equalsIgnoreCase(java.lang.String)' on a null object reference

**Comment by SherlockGougou** [comment]
可以多一些描述信息吗？比如如何产生的，能否重现。
