### ISSUE TITLE
加载原图失败，为什么呀，求指教

### ISSUE THREAD

**Issue by madreain** [SherlockGougou/BigImageViewPager#98]
加载原图链接："http://htmlstoretest.goujiawang.com/bbc/acf/constructionAlbum/2020/05/07/1ac1fd02328e9ae4d7727e4b74b2b763.jpeg"

**Comment by SherlockGougou** [comment]
麻烦提供一下日志，加载失败会有日志的。

**Comment by madreain** [comment]
images中直接加入上面的链接去查看原图，就直接一直显示进度是1%

**Comment by SherlockGougou** [comment]
如果你一张图片只有一个链接（不区分缩略图和原图），怎么会有查看原图这一说呢？

**Comment by SherlockGougou** [comment]
![image](https://user-images.githubusercontent.com/17920617/81468059-b3fba680-920f-11ea-9e86-8db053717461.png)

**Comment by madreain** [comment]
缩图后面加这个  ?x-oss-process=image//quality,Q_70/format,webp 
这样的不行

**Comment by SherlockGougou** [comment]
有木有缩略图取决于你们图片CDN；如果只有一张图片，可以配置隐藏查看原图。

**Comment by madreain** [comment]
好的，谢谢指教
