### ISSUE TITLE
能否把下载 或者返回按钮的点击事件开放出来

### ISSUE THREAD

**Issue by sceneren** [SherlockGougou/BigImageViewPager#99]
现在的需求,需要统计下载按钮的点击事件.目前的做法,只能改源代码.能否把点击事件开放出来,然后通过super去处理下载,自己也能添加需要的统计代码等功能.

还有个问题就是有的图片能放大很多,有的图片就只能放大一点

**Comment by SherlockGougou** [comment]
1.点击事件这个这段时间会加上；
2.放大比例和图片的尺寸有关系，不是固定的。

**Comment by sceneren** [comment]
感谢.但是图片放大的比例确实有点小.看能否把可以放大的比例调大一点

**Comment by sceneren** [comment]
下载结果回调能否放出来,目前只有一个Toast的提示而且是写死在代码里面的,无法修改.可以给一个结果回调的事件,让我们自己处理下载成功或者失败后的逻辑

**Comment by SherlockGougou** [comment]
下载回调已经增加了：

BigImageViewPager 发布6.1.0版本：
部分代码重构，新增下载监听（可选是否拦截下载行为）：

// 下载按钮点击回调，可以拦截下载逻辑，从而实现自己下载或埋点统计
.setDownloadClickListener(new OnDownloadClickListener() {
    @Override
    public void onClick(Activity activity, View view, int position) {
        // 可以在此处执行您自己的下载逻辑、埋点统计等信息
        Log.d(TAG, "onClick: position = " + position);
    }
    
    @Override
    public boolean isInterceptDownload() {
        // return true 时, 需要自己实现下载
        // return false 时, 使用内置下载
        return false;
    }
})

implementation 'com.github.SherlockGougou:BigImageViewPager:androidx-6.1.0'
implementation 'com.github.SherlockGougou:BigImageViewPager:v4_6.1.0'
